#!/usr/bin/env node
// Split the settlement kit into a core and its example modules (A3 offline
// step, docs/STOCKTAKE-WAVE-2B-v0.md §B2; the Stocktake Run's E1 arms).
//
//   node tools/golden-prompts/split-kit.mjs [--kit docs/kits/settlement-author.md] [--out docs/kits]
//
// The core is the kit with every fenced example withheld and the three
// worked-example sections removed whole (§8 Worked terrain patterns, §11
// Worked settlement fragments, §13 Complete example) — the contracts, the
// schema, the laws and the tables, and nothing the model could copy. Each
// withheld fence leaves a one-line marker naming the module it went to, so
// the prose that says "the example above" still points somewhere.
//
// The modules are the fences, grouped by the section that held them, each a
// small markdown file under `<out>/modules/` with the section's heading and
// the fences verbatim. The kit fences examples per *topic* (only one of its
// 67 fences names a form pack), so these are topic modules; per-pack modules
// are a kit-writing job, not a split.
//
// Deterministic and pure: same kit in, same files out; byte counts printed.
import fs from "node:fs";
import path from "node:path";

const args = process.argv.slice(2);
const opt = (n, d) => (args.includes(n) ? args[args.indexOf(n) + 1] : d);
const kitPath = opt("--kit", "docs/kits/settlement-author.md");
const outDir = opt("--out", "docs/kits");

const WORKED = [/^## 8\. Worked terrain patterns/, /^## 11\. Worked settlement fragments/, /^## 13\. Complete example/];

const slug = (h) =>
  h.replace(/^#+\s*/, "").replace(/`/g, "").replace(/[—–].*$/, "").replace(/@0/g, "").replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-|-$/g, "").toLowerCase().slice(0, 40) || "misc";

export function splitKit(text) {
  const lines = text.split("\n");
  const core = [];
  const modules = new Map(); // slug -> { heading, fences: string[] }
  let heading = "# Settlement author kit";
  let level = 1;
  let inFence = false;
  let fence = [];
  let skipping = false; // inside a worked section
  let withheldFences = 0;
  let withheldBytes = 0;
  let removedSectionBytes = 0;
  for (const line of lines) {
    if (!inFence && /^#{1,3} /.test(line)) {
      const lv = line.match(/^(#+)/)[1].length;
      if (skipping && lv <= 2) skipping = false;
      if (!skipping && WORKED.some((re) => re.test(line))) {
        skipping = true;
        level = lv;
        heading = line;
      }
      if (!skipping) {
        heading = line;
        level = lv;
      }
    }
    if (line.startsWith("```")) {
      if (!inFence) {
        inFence = true;
        fence = [line];
      } else {
        fence.push(line);
        inFence = false;
        const s = slug(heading);
        const m = modules.get(s) ?? { heading, fences: [] };
        m.fences.push(fence.join("\n"));
        modules.set(s, m);
        withheldFences++;
        withheldBytes += fence.join("\n").length + 1;
        if (!skipping) core.push(`*(example withheld — module \`${s}\`)*`);
      }
      continue;
    }
    if (inFence) {
      fence.push(line);
      continue;
    }
    if (skipping) {
      removedSectionBytes += line.length + 1;
      continue;
    }
    core.push(line);
  }
  return { core: core.join("\n"), modules, withheldFences, withheldBytes, removedSectionBytes };
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  const text = fs.readFileSync(kitPath, "utf8");
  const r = splitKit(text);
  const coreHeader =
    "<!-- settlement-core.md: generated by tools/golden-prompts/split-kit.mjs from settlement-author.md — " +
    "the kit with every fenced example withheld and the worked-example sections removed. Do not edit; regenerate. -->\n";
  fs.writeFileSync(path.join(outDir, "settlement-core.md"), coreHeader + r.core + "\n");
  const modDir = path.join(outDir, "modules");
  fs.mkdirSync(modDir, { recursive: true });
  for (const f of fs.readdirSync(modDir)) if (f.endsWith(".md")) fs.unlinkSync(path.join(modDir, f));
  const index = [];
  for (const [s, m] of r.modules) {
    const body = `<!-- module ${s}: fenced examples of the settlement kit section "${m.heading.replace(/^#+\s*/, "")}", generated by split-kit.mjs. -->\n${m.heading}\n\n${m.fences.join("\n\n")}\n`;
    fs.writeFileSync(path.join(modDir, `${s}.md`), body);
    index.push({ module: s, heading: m.heading.replace(/^#+\s*/, ""), fences: m.fences.length, bytes: body.length });
  }
  fs.writeFileSync(path.join(modDir, "index.json"), JSON.stringify(index, null, 2) + "\n");
  console.log(`kit ${text.length} B → core ${r.core.length} B (${Math.round((100 * r.core.length) / text.length)} %); withheld ${r.withheldFences} fences ${r.withheldBytes} B; worked sections removed ${r.removedSectionBytes} B; ${r.modules.size} modules`);
  for (const i of index) console.log(`  ${i.fences} fence(s) ${String(i.bytes).padStart(6)} B  ${i.module}`);
}
