/**
 * The author kit, read from disk at call time.
 *
 * The kit is the system prompt. It lives at `kits/settlement-author.md`,
 * generated by `tools/kit/build.mjs` from `kits/src/settlement-author.md` and
 * the code's own registries, so that the model, the human editing the source
 * and the tests that validate its examples all see the same bytes.
 *
 * One kit: the settlement profile is a superset of the terrain profile, and it
 * says a terrain-only document is the right answer for a wilderness prompt.
 */

import { readFile } from "node:fs/promises";
import path from "node:path";

import { findRepoRoot } from "./env.js";

/** The one kit an authoring run uses. */
export type KitName = "settlement";

/** The default kit for `terrainist generate`. */
export const DEFAULT_KIT: KitName = "settlement";

/** Path of the author kit, relative to the repo root. */
export const SETTLEMENT_KIT_RELATIVE_PATH = path.join("kits", "settlement-author.md");

/** Repo-relative path of a kit by name. */
export function kitRelativePath(_kit: KitName = "settlement"): string {
  return SETTLEMENT_KIT_RELATIVE_PATH;
}

/** Read the settlement-author kit. */
export async function loadSettlementAuthorKit(repoRoot?: string): Promise<string> {
  return await loadAuthorKit("settlement", repoRoot);
}

/** Read a kit by name. */
export async function loadAuthorKit(_kit: KitName = "settlement", repoRoot?: string): Promise<string> {
  const root = repoRoot ?? findRepoRoot();
  return await readFile(path.join(root, SETTLEMENT_KIT_RELATIVE_PATH), "utf8");
}
