/**
 * The human-review rig — one exhibit, one platform, one verdict.
 *
 * The dev world is a *contact sheet*: every exhibit the grammar can produce,
 * laid out edge to edge on one plain, so a build can be diffed against the one
 * before it by eye. That is the right shape for spotting a regression and the
 * wrong shape for collecting an opinion. Standing in it, a reviewer sees nine
 * buildings at once, has no way to say which one the note is about, and no way
 * to get the note out of the game at all.
 *
 * The rig is the same registry — literally the same cells, read from
 * {@link planDevGrid} and {@link planPropExhibits} — rearranged around the act
 * of reviewing. Each exhibit gets a **station**: a platform floating in the
 * void with exactly one structure on it, so there is nothing else in frame to
 * confuse the judgement, and a small bank of machinery that makes the review
 * loop a thing you can do with your hands:
 *
 * - a **pressure plate** at the spot you arrive on, sitting on a command block
 *   that `say`s `>> STATION <id>`. That line lands in the client log, and it is
 *   what lets everything said afterwards be attributed to *this* exhibit;
 * - **NEXT** and **PREV** buttons that teleport to the adjacent station,
 *   wrapping at both ends, so the whole set can be walked without a map;
 * - **PASS** and **FAIL** buttons that `say VERDICT <id> pass|fail`;
 * - **signs** naming the station and its parameters, so the thing you are
 *   looking at is identified in the world and not only in a manifest.
 *
 * Nothing here talks to a model, and nothing here reads the clock: the rig is
 * generated by pure code from the pinned seed, so re-running it after a
 * grammar change produces the same stations in the same places and the
 * previous session's notes still join.
 *
 * ## Why this file writes its own chunks
 *
 * Every other world in this compiler is materialized by {@link emitTerrain},
 * which fills every column of its region from bedrock up. That is exactly
 * wrong here: the point of a station is that the exhibit stands alone against
 * sky on every side, and a shared plain is precisely the confound the rig
 * exists to remove. So the rig keeps a column plan — the generators need one,
 * and the harbour props need a pond dug into one — but materializes only the
 * columns inside a platform, and only down to {@link RIG_PLATFORM_FLOOR}.
 * Everything else is void.
 */

import { writeFile } from "node:fs/promises";
import path from "node:path";

import {
  assignMaterials,
  nodeSeed,
  pickTheme,
  propFootprint,
  type BuildingMaterials,
  type StructureYaw,
} from "@terrainist/stdlib";
import type { PortDeclaration } from "@terrainist/spec";

import { commandBlockEntity, signEntity, type BlockEntity } from "./emit/block-entities.js";
import { applyConnectionStates, type ConnectionStats } from "./emit/connections.js";
import { EMIT_MINECRAFT_VERSION } from "./emit/world.js";
import { loadPrismarine, WORLD_MIN_Y, type EmitChunk, type PrismarineStack } from "./emit/prismarine.js";
import { writeWorldFiles } from "./emit/write.js";
import { FluidKind, type ColumnPlan } from "./terrain/columns.js";
import {
  buildBuildings,
  type BuildingJob,
  type BuiltBuilding,
  type StructureBlock,
} from "./structures/buildings.js";
import { buildProps, type PlacedProp, type PropJob } from "./structures/props.js";
import { digPropPond, planPropExhibits, type PropExhibit } from "./exhibits/props.js";
import { DEV_GROUND_Y, devColumnPlan, exhibitParams, planDevGrid, type DevExhibit } from "./devworld.js";

/* -------------------------------------------------------------------------- */
/* constants                                                                   */
/* -------------------------------------------------------------------------- */

/** World Y of every platform's top surface. */
export const RIG_GROUND_Y = DEV_GROUND_Y;

/**
 * World Y of the bottom of a platform.
 *
 * Deep enough for anything the grammar sinks into the ground: the foundation
 * skirt reaches `MAX_FOUNDATION_DEPTH` (12) and a cellar goes further, so 24
 * courses of stone leave the deepest exhibit standing on rock rather than
 * hanging out of the underside of its own platform.
 */
export const RIG_PLATFORM_FLOOR = RIG_GROUND_Y - 24;

/** Clear platform around the structure, in blocks. */
export const RIG_MARGIN = 4;

/** Depth of the machinery strip along a platform's south edge, in blocks. */
export const RIG_APRON = 7;

/** Void between two platforms, in blocks — generous, so no two stations share a frame. */
export const RIG_GAP = 24;

/** Narrowest a platform may be: the machinery bank needs eleven columns. */
export const RIG_MIN_WIDTH = 11 + RIG_MARGIN * 2;

/** The pinned seed. The rig is a fixture, so it never rerolls. */
export const RIG_WORLD_SEED = 20260729n;

/** The world folder name, and the level name inside `level.dat`. */
export const RIG_WORLD_NAME = "review_rig";

/** The manifest file name, alongside the world folder. */
export const RIG_MANIFEST_NAME = `${RIG_WORLD_NAME}.manifest.json`;

/** The station id the spawn platform announces. */
export const RIG_SPAWN_ID = "_start";

/**
 * Button positions along the machinery wall, as offsets from its centre.
 *
 * Two apart, because each button carries a label sign directly above it and
 * adjacent signs on a wall run their text together at a glance.
 */
export const RIG_BUTTON_SLOTS: readonly number[] = Object.freeze([-3, -1, 1, 3]);

/**
 * `commandBlockOutput`, off.
 *
 * Every button press and every plate step is a `say`, and with the rule at its
 * default each one *also* prints an operator-feedback line — so a walk through
 * a hundred stations doubles its own log and the chat box scrolls the sign you
 * were reading off the screen. The name is the 1.21.9+ one; the old camelCase
 * spelling is silently dropped at this DataVersion.
 */
export const RIG_GAME_RULES: Readonly<Record<string, boolean | number>> = Object.freeze({
  "minecraft:command_block_output": false,
  // Nothing in the rig grows, burns, melts or wanders, and a review session is
  // long: a frozen world is one that looks the same at the end of it.
  "minecraft:do_daylight_cycle": false,
  "minecraft:do_weather_cycle": false,
  "minecraft:do_mob_spawning": false,
  "minecraft:do_fire_tick": false,
  "minecraft:random_tick_speed": 0,
});

/* -------------------------------------------------------------------------- */
/* the plan                                                                    */
/* -------------------------------------------------------------------------- */

/** What a station is exhibiting. */
export type RigStationKind = "building" | "prop" | "spawn";

/** Where a station's exhibit came from — enough to regenerate it exactly. */
export interface RigProvenance {
  readonly kind: RigStationKind;
  /** The registry row this cell belongs to, e.g. `"cottage"`, `"harbour"`. */
  readonly row: string;
  /** Position within the row, west to east. */
  readonly column: number;
  /** The generator family: an archetype name, or a prop name. */
  readonly family: string;
  /** The node path the seed is derived from — the same one the dev world uses. */
  readonly nodePath: string;
  readonly theme?: string;
  readonly roof?: string;
  readonly floors?: number;
  /** Unrotated extents, as the row laid the cell out. */
  readonly size: readonly [number, number, number];
  /** The cell's `seedSalt`, when its row rerolls rather than varies. */
  readonly seedSalt?: string;
  /** Extra generator params the cell carries. */
  readonly params?: Readonly<Record<string, unknown>>;
}

/** An inclusive rectangle of world columns, with the Y its top sits at. */
export interface RigRect {
  readonly x0: number;
  readonly z0: number;
  readonly x1: number;
  readonly z1: number;
  readonly y: number;
}

/** Where a teleport lands, and the command string that gets there. */
export interface RigLanding {
  readonly x: number;
  readonly y: number;
  readonly z: number;
  /** The `tp` argument triple — block centres, so the player lands on the plate. */
  readonly tp: string;
}

/** One station, planned. */
export interface RigStation {
  /** Index in walk order; the spawn station is not in this sequence. */
  readonly index: number;
  readonly id: string;
  readonly kind: RigStationKind;
  readonly grid: { readonly col: number; readonly row: number };
  readonly platform: RigRect;
  readonly landing: RigLanding;
  /** Where the exhibit itself stands; absent on the spawn station. */
  readonly structure?: RigRect;
  /** Station ids the NEXT and PREV buttons go to. */
  readonly next: string;
  readonly prev: string;
  readonly provenance: RigProvenance;
}

/** The whole rig, before anything is built. */
export interface RigPlan {
  readonly spawn: RigStation;
  readonly stations: readonly RigStation[];
  /** Columns spanned by every platform, for the column plan's region. */
  readonly region: { readonly x0: number; readonly z0: number; readonly width: number; readonly depth: number };
  readonly columns: number;
}

/** One exhibit as the rig sees it, before it is given a platform. */
interface RigCell {
  readonly id: string;
  readonly kind: "building" | "prop";
  /** Extents on the ground the platform has to fit, already rotated. */
  readonly footprint: readonly [number, number];
  readonly provenance: RigProvenance;
  /** The dev-world cell this came from, for the builder. */
  readonly exhibit?: DevExhibit;
  readonly prop?: PropExhibit;
}

/** Rotated ground extents of a prop cell. */
function propExtents(cell: PropExhibit): [number, number] {
  const yaw = (cell.params["yaw"] ?? 0) as StructureYaw;
  const [w, , d] = cell.size;
  return yaw === 90 || yaw === 270 ? [d, w] : [w, d];
}

/**
 * Every exhibit in the registry, in station order.
 *
 * Read from the dev world's own planner rather than from the row files
 * directly, so a row added to the dev world shows up here without this file
 * being touched — the same argument that made `EXTRA_EXHIBIT_ROWS` a seam.
 * The context strips are excluded: a context cell is a building *and its
 * ground*, and putting one on a flat platform would exhibit neither.
 */
export function rigCells(): readonly RigCell[] {
  const cells: RigCell[] = [];
  for (const e of planDevGrid().exhibits) {
    cells.push({
      id: `${e.row}__${e.id}`,
      kind: "building",
      footprint: [e.size[0], e.size[2]],
      exhibit: e,
      provenance: {
        kind: "building",
        row: e.row,
        column: e.column,
        family: e.archetype,
        nodePath: `rig.${e.row}.${e.id}`,
        theme: e.theme,
        roof: e.roof,
        floors: e.floors,
        size: e.size,
        ...(e.seedSalt === undefined ? {} : { seedSalt: e.seedSalt }),
        ...(e.params === undefined ? {} : { params: e.params }),
      },
    });
  }
  for (const p of planPropExhibits().exhibits) {
    cells.push({
      id: `prop_${p.row}__${p.id}`,
      kind: "prop",
      footprint: propExtents(p),
      prop: p,
      provenance: {
        kind: "prop",
        row: p.row,
        column: p.column,
        family: p.prop,
        nodePath: `rig.props.${p.row}.${p.id}`,
        theme: p.theme,
        size: p.size,
        params: p.params,
      },
    });
  }
  return cells;
}

/** Platform extents for a cell's ground footprint. */
function platformSize(footprint: readonly [number, number]): [number, number] {
  const width = Math.max(footprint[0] + RIG_MARGIN * 2, RIG_MIN_WIDTH);
  const depth = footprint[1] + RIG_MARGIN * 2 + RIG_APRON;
  return [width, depth];
}

/** Block-centre coordinates for a `tp` argument triple. */
function tpTriple(x: number, y: number, z: number): string {
  return `${x + 0.5} ${y} ${z + 0.5}`;
}

/**
 * Lay every station out.
 *
 * A square-ish grid on a uniform pitch, in registry order, reading west to
 * east and then south — so "station 40" is somewhere you can find by walking,
 * and NEXT follows the same order the manifest does. Platforms are sized per
 * station and left-aligned in their cell, because a uniform platform big
 * enough for the widest exhibit would put a cottage in the middle of an acre.
 */
export function planReviewRig(): RigPlan {
  const cells = rigCells();
  const sizes = cells.map((c) => platformSize(c.footprint));
  const spawnSize: [number, number] = [RIG_MIN_WIDTH, RIG_MIN_WIDTH + RIG_APRON];

  const pitchX = Math.max(spawnSize[0], ...sizes.map((s) => s[0])) + RIG_GAP;
  const pitchZ = Math.max(spawnSize[1], ...sizes.map((s) => s[1])) + RIG_GAP;
  // The spawn platform takes the first grid cell, so the walk starts where the
  // player does and the numbering of the stations still starts at one.
  const cols = Math.ceil(Math.sqrt(cells.length + 1));

  const place = (slot: number, size: readonly [number, number]) => {
    const col = slot % cols;
    const row = Math.floor(slot / cols);
    const x0 = col * pitchX;
    const z0 = row * pitchZ;
    const platform: RigRect = {
      x0,
      z0,
      x1: x0 + size[0] - 1,
      z1: z0 + size[1] - 1,
      y: RIG_GROUND_Y,
    };
    const cx = x0 + (size[0] >> 1);
    const cz = z0 + size[1] - 5;
    const landing: RigLanding = {
      x: cx,
      y: RIG_GROUND_Y + 1,
      z: cz,
      tp: tpTriple(cx, RIG_GROUND_Y + 1, cz),
    };
    return { col, row, platform, landing };
  };

  const spawnPlaced = place(0, spawnSize);
  const stations: RigStation[] = cells.map((cell, i) => {
    const size = sizes[i] as [number, number];
    const p = place(i + 1, size);
    const sw = cell.footprint[0];
    const sd = cell.footprint[1];
    const sx = p.platform.x0 + ((size[0] - sw) >> 1);
    const sz = p.platform.z0 + RIG_MARGIN;
    return {
      index: i,
      id: cell.id,
      kind: cell.kind,
      grid: { col: p.col, row: p.row },
      platform: p.platform,
      landing: p.landing,
      structure: { x0: sx, z0: sz, x1: sx + sw - 1, z1: sz + sd - 1, y: RIG_GROUND_Y },
      // Wrapping, at both ends: a reviewer who overshoots the last station
      // should arrive at the first, not walk off the end of the world.
      next: (cells[(i + 1) % cells.length] as RigCell).id,
      prev: (cells[(i - 1 + cells.length) % cells.length] as RigCell).id,
      provenance: cell.provenance,
    };
  });

  const spawn: RigStation = {
    index: -1,
    id: RIG_SPAWN_ID,
    kind: "spawn",
    grid: { col: spawnPlaced.col, row: spawnPlaced.row },
    platform: spawnPlaced.platform,
    landing: spawnPlaced.landing,
    next: (stations[0] as RigStation).id,
    prev: (stations[stations.length - 1] as RigStation).id,
    provenance: {
      kind: "spawn",
      row: "_start",
      column: 0,
      family: "instructions",
      nodePath: "rig._start",
      size: [spawnSize[0], 1, spawnSize[1]],
    },
  };

  const all = [spawn, ...stations];
  const x0 = Math.min(...all.map((s) => s.platform.x0)) - 2;
  const z0 = Math.min(...all.map((s) => s.platform.z0)) - 2;
  const x1 = Math.max(...all.map((s) => s.platform.x1)) + 2;
  const z1 = Math.max(...all.map((s) => s.platform.z1)) + 2;
  const columns = all.reduce(
    (sum, s) => sum + (s.platform.x1 - s.platform.x0 + 1) * (s.platform.z1 - s.platform.z0 + 1),
    0,
  );

  return {
    spawn,
    stations,
    region: { x0, z0, width: x1 - x0 + 1, depth: z1 - z0 + 1 },
    columns,
  };
}

/* -------------------------------------------------------------------------- */
/* the machinery                                                               */
/* -------------------------------------------------------------------------- */

/** One button on the machinery wall. */
export interface RigButton {
  /** Slot index into {@link RIG_BUTTON_SLOTS}. */
  readonly slot: number;
  readonly label: string;
  /** Second sign line — what the button does, in three words. */
  readonly hint: string;
  readonly command: string;
}

/** The machinery a station carries, as blocks and compounds. */
interface Machinery {
  readonly blocks: readonly StructureBlock[];
  readonly entities: readonly BlockEntity[];
}

/**
 * The four commands a station's buttons run.
 *
 * Exported because the manifest↔world test asserts on exactly these strings:
 * the property that matters is that the command block on the platform runs the
 * command the manifest says it does, and a test that rebuilt the string from
 * its own template would only be checking itself.
 */
export function rigButtons(station: RigStation, byId: ReadonlyMap<string, RigStation>): RigButton[] {
  const landingOf = (id: string): string =>
    (byId.get(id) as RigStation).landing.tp;
  const buttons: RigButton[] = [
    { slot: 0, label: "NEXT", hint: "go forward", command: `tp @p ${landingOf(station.next)}` },
  ];
  if (station.kind === "spawn") return buttons;
  buttons.push(
    { slot: 1, label: "PREV", hint: "go back", command: `tp @p ${landingOf(station.prev)}` },
    { slot: 2, label: "PASS", hint: "looks right", command: `say VERDICT ${station.id} pass` },
    { slot: 3, label: "FAIL", hint: "looks wrong", command: `say VERDICT ${station.id} fail` },
  );
  return buttons;
}

/** The command the arrival plate's command block runs. */
export function rigArrivalCommand(station: RigStation): string {
  return `say >> STATION ${station.id}`;
}

/**
 * The two label signs a station carries, as their four lines each.
 *
 * One says what the station *is* — its id and its place in the registry — and
 * one says what the generator was *told*, which is the pair a reviewer needs
 * to turn "this roof is wrong" into a reproducible complaint.
 */
export function rigSignLines(station: RigStation): [string[], string[]] {
  const p = station.provenance;
  if (station.kind === "spawn") {
    return [
      ["REVIEW RIG", "", "step on the plate", "press NEXT"],
      ["PASS / FAIL", "record a verdict", "type in chat to", "leave a comment"],
    ];
  }
  const size = `${p.size[0]}x${p.size[1]}x${p.size[2]}`;
  const extras = Object.keys(p.params ?? {}).join(" ");
  return [
    [`#${station.index + 1} ${p.row}`, truncate(station.id, 15), p.family, `col ${p.column}`],
    [
      `size ${size}`,
      p.roof === undefined ? `theme ${p.theme ?? "-"}` : `roof ${p.roof} f${p.floors ?? 1}`,
      p.roof === undefined ? extras : `theme ${p.theme ?? "-"}`,
      p.seedSalt === undefined ? extras : `salt ${p.seedSalt}`,
    ],
  ];
}

/** The four instruction signs on the spawn platform. */
const RIG_INSTRUCTIONS: readonly (readonly string[])[] = Object.freeze([
  ["HOW THIS WORKS", "1. press NEXT", "2. look at the", "   one building"],
  ["3. PASS or FAIL", "4. say anything", "   in chat: it", "   is recorded"],
  ["the plate you", "land on marks", "which station", "your notes join"],
  ["NEXT wraps at", "the last one.", "nothing here", "is destructive."],
]);

function truncate(text: string, max: number): string {
  return text.length <= max ? text : `${text.slice(0, max - 1)}~`;
}

/**
 * Build one station's machinery.
 *
 * The geometry is fixed relative to the platform's south edge, which is what
 * makes the rig navigable: the plate is always four blocks north of the wall,
 * the wall always carries the buttons in the same order, and a reviewer who
 * has done one station has done all of them.
 */
function buildMachinery(
  station: RigStation,
  buttons: readonly RigButton[],
  stack: PrismarineStack,
): Machinery {
  const blocks: StructureBlock[] = [];
  const entities: BlockEntity[] = [];
  const y = RIG_GROUND_Y;
  const state = (name: string, props?: Record<string, string>): number =>
    (props === undefined ? stack.blockByName(name)?.stateId : stack.blockStateOf(name, props)) ?? 0;

  const cx = station.landing.x;
  const zWall = station.platform.z1 - 1;
  const zButtons = zWall - 1;
  const zLand = station.landing.z;

  // --- the arrival plate, on its command block ------------------------------
  // The plate strongly powers the block beneath it, so an impulse command
  // block directly under the landing spot fires once per arrival — which is
  // exactly the granularity the log harvester wants.
  blocks.push({ x: cx, y, z: zLand, stateId: state("command_block", { conditional: "false", facing: "up" }) });
  blocks.push({
    x: cx,
    y: y + 1,
    z: zLand,
    stateId: state("stone_pressure_plate", { powered: "false" }),
  });
  entities.push(
    commandBlockEntity(cx, y, zLand, rigArrivalCommand(station), {
      auto: false,
      trackOutput: false,
      customName: "@",
    }),
  );

  // --- the label signs -----------------------------------------------------
  // Standing signs on the platform, one either side of the plate, facing south
  // so they read from the spot the player lands on.
  const [lineA, lineB] = rigSignLines(station);
  const signState = state("oak_sign", { rotation: "0", waterlogged: "false" });
  for (const [dx, lines] of [
    [-2, lineA],
    [2, lineB],
  ] as const) {
    blocks.push({ x: cx + dx, y: y + 1, z: zLand - 1, stateId: signState });
    entities.push(signEntity(cx + dx, y + 1, zLand - 1, { front: lines, waxed: true }));
  }

  // --- the spawn platform's instructions -----------------------------------
  if (station.kind === "spawn") {
    for (const [i, lines] of RIG_INSTRUCTIONS.entries()) {
      const x = cx - 3 + i * 2;
      blocks.push({ x, y: y + 1, z: zLand - 3, stateId: signState });
      entities.push(signEntity(x, y + 1, zLand - 3, { front: lines, waxed: true }));
    }
  }

  // --- the machinery wall --------------------------------------------------
  // Two courses of brick from `cx - 4` to `cx + 4`, with a command block
  // standing in the lower course behind each button. The button is on the
  // wall's north face, so it is pressed from the platform, and its label sign
  // is on the same face one block up.
  const bricks = state("stone_bricks");
  const slotOf = new Map(buttons.map((b) => [RIG_BUTTON_SLOTS[b.slot] as number, b]));
  for (let dx = -4; dx <= 4; dx++) {
    const x = cx + dx;
    const button = slotOf.get(dx);
    blocks.push({
      x,
      y: y + 1,
      z: zWall,
      stateId:
        button === undefined
          ? bricks
          : state("command_block", { conditional: "false", facing: "up" }),
    });
    blocks.push({ x, y: y + 2, z: zWall, stateId: bricks });
    if (button === undefined) continue;
    entities.push(
      commandBlockEntity(x, y + 1, zWall, button.command, {
        auto: false,
        trackOutput: false,
        customName: button.label,
      }),
    );
    blocks.push({
      x,
      y: y + 1,
      z: zButtons,
      stateId: state("stone_button", { face: "wall", facing: "north", powered: "false" }),
    });
    blocks.push({
      x,
      y: y + 2,
      z: zButtons,
      stateId: state("oak_wall_sign", { facing: "north", waterlogged: "false" }),
    });
    entities.push(
      signEntity(x, y + 2, zButtons, {
        front: [button.label, button.hint, "", ""],
        waxed: true,
      }),
    );
  }

  return { blocks, entities };
}

/* -------------------------------------------------------------------------- */
/* the build                                                                   */
/* -------------------------------------------------------------------------- */

/** The door port every exhibit declares — the same one the dev world uses. */
const RIG_PORTS: Readonly<Record<string, PortDeclaration>> = Object.freeze({
  door: { type: "door", face: "south", tags: ["primary"] } as PortDeclaration,
});

/** What {@link buildReviewRig} produced. */
export interface RigResult {
  readonly plan: RigPlan;
  readonly manifest: RigManifest;
  readonly worldDir: string;
  readonly manifestPath: string;
  readonly levelDatPath: string;
  readonly regionFiles: readonly string[];
  readonly chunkCount: number;
  readonly blockCount: number;
  /** Columns dug and flooded for the harbour stations' basins. */
  readonly pondColumns: number;
  readonly blockEntityCount: number;
  readonly stationCount: number;
  readonly buildings: readonly BuiltBuilding[];
  readonly placedProps: readonly PlacedProp[];
  /** Every block the generators and the machinery emitted, in build order. */
  readonly structureBlocks: readonly StructureBlock[];
  readonly entities: readonly BlockEntity[];
  readonly connections: ConnectionStats;
  readonly minecraftVersion: string;
  readonly dataVersion: number;
}

/** The manifest, as written next to the world. */
export interface RigManifest {
  readonly format: "terrainist-review-rig/1";
  readonly world: string;
  readonly minecraftVersion: string;
  readonly dataVersion: number;
  readonly worldSeed: string;
  readonly groundY: number;
  readonly gameRules: Readonly<Record<string, boolean | number>>;
  readonly stationCount: number;
  readonly spawn: RigManifestStation;
  readonly stations: readonly RigManifestStation[];
}

/** One station in the manifest — everything needed to join a note back. */
export interface RigManifestStation {
  readonly index: number;
  readonly id: string;
  readonly kind: RigStationKind;
  readonly grid: { readonly col: number; readonly row: number };
  readonly platform: RigRect;
  readonly landing: RigLanding;
  readonly structure?: RigRect;
  readonly next: string;
  readonly prev: string;
  /** The commands the station's command blocks carry, by machine role. */
  readonly commands: Readonly<Record<string, string>>;
  readonly provenance: RigProvenance;
}

/** The manifest for a plan — pure, so a test can build it without a world. */
export function rigManifest(plan: RigPlan, stack: PrismarineStack): RigManifest {
  const byId = stationIndex(plan);
  const entry = (s: RigStation): RigManifestStation => {
    const commands: Record<string, string> = { arrive: rigArrivalCommand(s) };
    for (const b of rigButtons(s, byId)) commands[b.label.toLowerCase()] = b.command;
    return {
      index: s.index,
      id: s.id,
      kind: s.kind,
      grid: s.grid,
      platform: s.platform,
      landing: s.landing,
      ...(s.structure === undefined ? {} : { structure: s.structure }),
      next: s.next,
      prev: s.prev,
      commands,
      provenance: s.provenance,
    };
  };
  return {
    format: "terrainist-review-rig/1",
    world: RIG_WORLD_NAME,
    minecraftVersion: stack.minecraftVersion,
    dataVersion: stack.dataVersion,
    worldSeed: RIG_WORLD_SEED.toString(),
    groundY: RIG_GROUND_Y,
    gameRules: RIG_GAME_RULES,
    stationCount: plan.stations.length,
    spawn: entry(plan.spawn),
    stations: plan.stations.map(entry),
  };
}

/** Every station by id, spawn included. */
export function stationIndex(plan: RigPlan): Map<string, RigStation> {
  const byId = new Map<string, RigStation>();
  byId.set(plan.spawn.id, plan.spawn);
  for (const s of plan.stations) byId.set(s.id, s);
  return byId;
}

/**
 * Build the rig and write it into `outDir/review_rig`, with its manifest
 * alongside.
 */
export async function buildReviewRig(outDir: string): Promise<RigResult> {
  const stack = loadPrismarine(EMIT_MINECRAFT_VERSION);
  const plan = planReviewRig();
  const byId = stationIndex(plan);
  const cells = rigCells();

  // The column plan is a *substrate*, not the world: the generators sample it
  // for ground level and material, the pond digger writes into it, and only
  // the columns inside a platform are ever materialized.
  const columnPlan = devColumnPlan(
    { x0: plan.region.x0, z0: plan.region.z0, width: plan.region.width, depth: plan.region.depth },
    stack,
  );

  // --- ponds, before anything stands on them -------------------------------
  // A harbour prop only exists over water, and the placer measures itself
  // against the finished plan, so every basin is dug first. The basin is the
  // station's structure rect grown by the margin, which keeps it clear of the
  // platform edge and so of the machinery.
  const waterRows = new Set(["harbour"]);
  let pondColumns = 0;
  for (const station of plan.stations) {
    if (station.kind !== "prop" || !waterRows.has(station.provenance.row)) continue;
    const r = station.structure as RigRect;
    pondColumns += digPropPond(
      columnPlan,
      { x0: r.x0 - 2, z0: r.z0 - 2, x1: r.x1 + 2, z1: r.z1 + 2 },
      stack,
    );
  }

  // --- the exhibits --------------------------------------------------------
  const buildingJobs: BuildingJob[] = [];
  const propJobs: PropJob[] = [];
  for (const [i, cell] of cells.entries()) {
    const station = plan.stations[i] as RigStation;
    const rect = station.structure as RigRect;
    const nodePath = cell.provenance.nodePath;
    if (cell.kind === "building") {
      const e = cell.exhibit as DevExhibit;
      const seed = nodeSeed(RIG_WORLD_SEED, nodePath, e.seedSalt ?? "");
      const theme = pickTheme(seed, e.theme);
      const materials = assignMaterials(theme, 1, seed)[0] as BuildingMaterials;
      buildingJobs.push({
        nodePath,
        placement: {
          nodePath,
          id: station.id,
          translation: [rect.x0, RIG_GROUND_Y, rect.z0] as [number, number, number],
          yaw: 0,
          mirror: false,
          size: e.size,
          footprint: { x0: rect.x0, z0: rect.z0, x1: rect.x1, z1: rect.z1 },
          anchor: { x: rect.x0 + ((e.size[0] - 1) >> 1), z: rect.z0 + ((e.size[2] - 1) >> 1) },
          foundationY: RIG_GROUND_Y,
        },
        size: e.size,
        params: exhibitParams(e),
        ports: RIG_PORTS,
        seed,
        tags: [e.archetype],
        materials,
      });
    } else {
      const p = cell.prop as PropExhibit;
      const seed = nodeSeed(RIG_WORLD_SEED, nodePath, "");
      const theme = pickTheme(seed, p.theme);
      const materials = assignMaterials(theme, 1, seed)[0] as BuildingMaterials;
      propJobs.push({
        nodePath,
        prop: p.prop,
        params: { ...p.params, at: { x: rect.x0, z: rect.z0 } },
        seed,
        materials,
      });
    }
  }

  const built = buildBuildings(buildingJobs, columnPlan, stack);
  const props = buildProps({ jobs: propJobs, plan: columnPlan, stack });

  // --- the machinery -------------------------------------------------------
  const machineryBlocks: StructureBlock[] = [];
  const entities: BlockEntity[] = [];
  for (const station of [plan.spawn, ...plan.stations]) {
    const m = buildMachinery(station, rigButtons(station, byId), stack);
    machineryBlocks.push(...m.blocks);
    entities.push(...m.entities);
  }

  // --- materialize ---------------------------------------------------------
  const structureBlocks = [...built.blocks, ...props.blocks, ...machineryBlocks];
  const chunks = new Map<string, EmitChunk>();
  const chunkFor = (cx: number, cz: number): EmitChunk => {
    const key = `${cx},${cz}`;
    let chunk = chunks.get(key);
    if (chunk === undefined) {
      chunk = stack.createChunk();
      paintChunkBiome(chunk, columnPlan.biome[0] as number);
      chunks.set(key, chunk);
    }
    return chunk;
  };

  let blockCount = 0;
  for (const station of [plan.spawn, ...plan.stations]) {
    blockCount += materializePlatform(chunkFor, columnPlan, station.platform);
  }
  for (const block of structureBlocks) {
    if (block.y < WORLD_MIN_Y || block.y > 319) continue;
    const cx = block.x >> 4;
    const cz = block.z >> 4;
    chunkFor(cx, cz).setStateId(block.x - cx * 16, block.y, block.z - cz * 16, block.stateId);
    blockCount++;
  }
  for (const entity of entities) {
    const cx = entity.x >> 4;
    const cz = entity.z >> 4;
    chunkFor(cx, cz).setBlockEntityNbt(entity.x, entity.y, entity.z, {
      ...entity.data,
      id: { type: "string", value: entity.id },
    });
  }

  // Fences, walls and panes store their neighbours in their own state and the
  // game never recomputes it, so the connection pass runs over the finished
  // world exactly as it does for a compiled one.
  const connections = applyConnectionStates(chunks, structureBlocks, stack);

  const worldDir = path.join(path.resolve(outDir), RIG_WORLD_NAME);
  const written = await writeWorldFiles({
    chunks,
    worldDir,
    levelName: RIG_WORLD_NAME,
    spawn: { x: plan.spawn.landing.x, y: plan.spawn.landing.y, z: plan.spawn.landing.z },
    stack,
    gameRules: RIG_GAME_RULES,
  });

  const manifest = rigManifest(plan, stack);
  const manifestPath = path.join(path.resolve(outDir), RIG_MANIFEST_NAME);
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

  return {
    plan,
    manifest,
    worldDir: written.worldDir,
    manifestPath,
    levelDatPath: written.levelDatPath,
    regionFiles: written.regionFiles,
    chunkCount: written.chunkCount,
    blockCount,
    pondColumns,
    blockEntityCount: entities.length,
    stationCount: plan.stations.length,
    buildings: built.built,
    placedProps: props.placed,
    structureBlocks,
    entities,
    connections,
    minecraftVersion: stack.minecraftVersion,
    dataVersion: stack.dataVersion,
  };
}

/**
 * Write one platform's columns out of the plan.
 *
 * A bounded, floored version of the terrain emitter's column fill: soil and
 * surface exactly as the plan holds them (so a dug basin arrives as sand and
 * water rather than as a hole in the grass), stone from there down to
 * {@link RIG_PLATFORM_FLOOR}, and nothing at all outside the rectangle. No
 * bedrock: the underside of a platform is meant to be *seen*, and a course of
 * bedrock under every station would read as a floor the world once had.
 */
function materializePlatform(
  chunkFor: (cx: number, cz: number) => EmitChunk,
  plan: ColumnPlan,
  rect: RigRect,
): number {
  const { region } = plan;
  const stone = plan.states.stone;
  let count = 0;
  for (let z = rect.z0; z <= rect.z1; z++) {
    const j = z - region.z0;
    if (j < 0 || j >= region.depth) continue;
    for (let x = rect.x0; x <= rect.x1; x++) {
      const i = x - region.x0;
      if (i < 0 || i >= region.width) continue;
      const idx = j * region.width + i;
      const chunk = chunkFor(x >> 4, z >> 4);
      const lx = x - (x >> 4) * 16;
      const lz = z - (z >> 4) * 16;

      const top = plan.ground[idx] as number;
      const soilDepth = plan.soil[idx] as number;
      const soilBase = top - soilDepth;
      if (soilBase - 1 >= RIG_PLATFORM_FLOOR) {
        chunk.fillColumn(lx, lz, RIG_PLATFORM_FLOOR, soilBase - 1, stone);
        count += soilBase - RIG_PLATFORM_FLOOR;
      }
      if (soilDepth > 0 && top - 1 >= soilBase) {
        chunk.fillColumn(lx, lz, soilBase, top - 1, plan.subsurface[idx] as number);
        count += top - soilBase;
      }
      chunk.setStateId(lx, top, lz, plan.surface[idx] as number);
      count += 1;

      const kind = plan.fluidKind[idx];
      if (kind !== FluidKind.NONE) {
        const fluidState = kind === FluidKind.LAVA ? plan.states.lava : plan.states.water;
        const surfaceY = plan.fluidTop[idx] as number;
        if (surfaceY > top) {
          chunk.fillColumn(lx, lz, top + 1, surfaceY, fluidState);
          count += surfaceY - top;
        }
      }
    }
  }
  return count;
}

/** Paint a whole chunk one biome, at the 4×4×4 resolution the format wants. */
function paintChunkBiome(chunk: EmitChunk, biomeId: number): void {
  for (let cellZ = 0; cellZ < 4; cellZ++) {
    for (let cellX = 0; cellX < 4; cellX++) {
      for (let y = WORLD_MIN_Y; y < WORLD_MIN_Y + 384; y += 4) {
        chunk.setBiomeAt(cellX * 4, y, cellZ * 4, biomeId);
      }
    }
  }
}
