/**
 * The **Terrarium** — the human-review world. One exhibit, one platform, one
 * verdict.
 *
 * The dev world is a *contact sheet*: every exhibit the grammar can produce,
 * laid out edge to edge on one plain, so a build can be diffed against the one
 * before it by eye. That is the right shape for spotting a regression and the
 * wrong shape for collecting an opinion. Standing in it, a reviewer sees nine
 * buildings at once, has no way to say which one the note is about, and no way
 * to get the note out of the game at all.
 *
 * The Terrarium is the same registry — literally the same cells, read from
 * {@link planDevGrid} and {@link planPropExhibits} — rearranged around the act
 * of reviewing. Each exhibit gets a **station**: a platform floating in the
 * void with exactly one structure on it, so there is nothing else in frame to
 * confuse the judgement, and a small bank of machinery that makes the review
 * loop a thing you can do with your hands:
 *
 * - a **pressure plate** at the spot you arrive on, sitting on a command block
 *   that `say`s `>> STATION <id>`. That line lands in the client log, and it is
 *   what lets everything said afterwards be attributed to *this* exhibit;
 * - two **travel cubes** — 3x3x3 volumes of air, one on either side of the
 *   landing, that teleport whoever flies into them to the next or the previous
 *   station, wrapping at both ends, so the whole set can be walked without a
 *   map;
 * - **signs** naming the station and its parameters, so the thing you are
 *   looking at is identified in the world and not only in a manifest.
 *
 * ## v3: spectator flight, and no buttons at all
 *
 * v1 and v2 asked the reviewer to *press* things: NEXT/PREV to move, PASS/FAIL
 * to record a verdict. A real session (Kai, 2026-07-30) showed both to be in
 * the way. A reviewer who is judging how a building *looks* wants to be in
 * spectator mode — through walls, through roofs, no fall damage, no
 * accidentally-broken exhibit — and a spectator cannot press a button or step
 * on a plate. And a verdict is a sentence, not a pair of buttons: it is typed
 * in chat like every other note, and the harvester already reads it there.
 *
 * So v3 deletes the button wall entirely and replaces it with a mechanism a
 * spectator *can* trigger: a fly-into region. Beside each landing sit two
 * marked pads — **lime** for NEXT, **red** for PREV — each with a repeating
 * command block buried under it testing `execute if entity @a[<the cube>]`,
 * and two conditional chain blocks behind it doing the teleport and then the
 * `say >> STATION <destination>` that the harvester joins notes on. The player
 * leaves the region in the same tick they are teleported out of it, so the
 * chain fires exactly once per entry.
 *
 * The world's default game mode is **spectator** (`GameType 3`), set once in
 * `level.dat` rather than enforced by a repeating `gamemode` command: a
 * reviewer who wants to drop into creative for a screenshot must be able to,
 * and a rig that fought that toggle every tick would be unusable.
 *
 * Nothing here talks to a model, and nothing here reads the clock: the
 * Terrarium is generated by pure code from the pinned seed, so re-running it
 * after a grammar change produces the same stations in the same places and the
 * previous session's notes still join.
 *
 * ## v2: the multi-structure stations
 *
 * A single-structure station is the right shape for judging a *generator* and
 * the wrong shape for judging the *pipeline*. Nothing above can be asked "does
 * the lane meet the door?", "does the tunnel connect the cellars?", "does a
 * plaza with four buildings read as a place?" — those are compositions, and the
 * only honest way to exhibit one is to compile one.
 *
 * So after the single-structure grid comes a band of **multi-structure
 * stations**, each owning a real settlement-profile mini-document that goes
 * through {@link compileTerrain} and is then transplanted onto its platform.
 * See `terrarium-stations.ts` for the documents and for why transplanting beats
 * stitching separate worlds. They carry exactly the same machinery — arrival
 * plate, NEXT/PREV, PASS/FAIL, signs — because the review loop must not change
 * shape halfway through the walk.
 *
 * ## Why this file writes its own chunks
 *
 * Every other world in this compiler is materialized by {@link emitTerrain},
 * which fills every column of its region from bedrock up. That is exactly
 * wrong here: the point of a station is that the exhibit stands alone against
 * sky on every side, and a shared plain is precisely the confound the Terrarium
 * exists to remove. So it keeps a column plan — the generators need one, and
 * the harbour props need a pond dug into one — but materializes only the
 * columns inside a platform, and only down to {@link TERRARIUM_PLATFORM_FLOOR}.
 * Everything else is void. A multi-station's columns come from its own
 * compiled plan instead, through the same bounded, floored writer.
 */

import { writeFile } from "node:fs/promises";
import path from "node:path";

import {
  assignMaterials,
  nodeSeed,
  pickTheme,
  propFootprint,
  type BuildingMaterials,
  type StructureYaw,
} from "@terrainist/stdlib";
import type { PortDeclaration } from "@terrainist/spec";

import { commandBlockEntity, signEntity, type BlockEntity } from "./emit/block-entities.js";
import { applyConnectionStates, type ConnectionStats } from "./emit/connections.js";
import { EMIT_MINECRAFT_VERSION } from "./emit/world.js";
import { loadPrismarine, WORLD_MIN_Y, type EmitChunk, type PrismarineStack } from "./emit/prismarine.js";
import { writeWorldFiles } from "./emit/write.js";
import type { Provenance } from "./provenance.js";
import { FluidKind, type ColumnPlan } from "./terrain/columns.js";
import {
  buildBuildings,
  type BuildingJob,
  type BuiltBuilding,
  type StructureBlock,
} from "./structures/buildings.js";
import { buildProps, type PlacedProp, type PropJob } from "./structures/props.js";
import {
  digPropPond,
  planPropExhibits,
  PROP_EXHIBIT_PLAN,
  type PropExhibit,
} from "./exhibits/props.js";
import { devColumnPlan, exhibitParams, planDevGrid, type DevExhibit } from "./devworld.js";
import {
  TERRARIUM_GROUND_Y,
  compileMiniStation,
  multiStationSpecs,
  type CompiledMiniStation,
  type MultiStationKind,
  type MultiStationSpec,
} from "./terrarium-stations.js";

export { TERRARIUM_GROUND_Y };

/* -------------------------------------------------------------------------- */
/* constants                                                                   */
/* -------------------------------------------------------------------------- */

/**
 * World Y of the bottom of a platform.
 *
 * Deep enough for anything the grammar sinks into the ground: the foundation
 * skirt reaches `MAX_FOUNDATION_DEPTH` (12) and a cellar goes further, so 24
 * courses of stone leave the deepest exhibit standing on rock rather than
 * hanging out of the underside of its own platform.
 */
export const TERRARIUM_PLATFORM_FLOOR = TERRARIUM_GROUND_Y - 24;

/** Clear platform around the structure, in blocks. */
export const TERRARIUM_MARGIN = 4;

/** Depth of the machinery strip along a platform's south edge, in blocks. */
export const TERRARIUM_APRON = 7;

/** Void between two platforms, in blocks — generous, so no two stations share a frame. */
export const TERRARIUM_GAP = 24;

/**
 * Narrowest a platform may be.
 *
 * Eleven columns plus the margin ring — which is also exactly what the two
 * travel cubes want: their pads span `landing.x - 7 .. landing.x + 7`, fifteen
 * columns, and the landing sits at the platform's midpoint.
 */
export const TERRARIUM_MIN_WIDTH = 11 + TERRARIUM_MARGIN * 2;

/** The pinned seed. The Terrarium is a fixture, so it never rerolls. */
export const TERRARIUM_WORLD_SEED = 20260729n;

/** Void between the single-structure grid and the multi-structure band. */
export const TERRARIUM_BAND_GAP = 64;

/** The world folder name, and the level name inside `level.dat`. */
export const TERRARIUM_WORLD_NAME = "terrarium";

/** The manifest file name, alongside the world folder. */
export const TERRARIUM_MANIFEST_NAME = `${TERRARIUM_WORLD_NAME}.manifest.json`;

/** The station id the spawn platform announces. */
export const TERRARIUM_SPAWN_ID = "_start";

/**
 * The world's default game mode: **spectator**.
 *
 * Set in `level.dat` rather than enforced by a repeating `gamemode` command,
 * so a reviewer who switches to creative for a screenshot stays there. Every
 * mechanism in the rig is chosen to work for a spectator: `@a` matches one, a
 * pressure plate does not.
 */
export const TERRARIUM_GAME_TYPE = 3;

/** Edge length of a travel cube, in blocks. */
export const TERRARIUM_CUBE_SIZE = 3;

/**
 * How far a travel cube's centre sits from the landing spot, in columns.
 *
 * Far enough that a teleport never drops the player inside the cube they would
 * immediately re-trigger (the cube's near face is four columns from the
 * landing, and the cubes are one deep either side of the landing row), and
 * near enough that both pads are in frame from the spot you arrive on. The
 * label signs stand at `landing.x ± 2`, so nothing overlaps.
 */
export const TERRARIUM_CUBE_OFFSET = 6;

/** The pad block under each travel cube, by direction. Lime forward, red back. */
export const TERRARIUM_CUBE_PADS: Readonly<Record<"next" | "prev", string>> = Object.freeze({
  next: "lime_concrete",
  prev: "red_concrete",
});

/** The pad's centre column, which reads as an arrow head from the air. */
export const TERRARIUM_CUBE_EYES: Readonly<Record<"next" | "prev", string>> = Object.freeze({
  next: "lime_glazed_terracotta",
  prev: "red_glazed_terracotta",
});

/**
 * `commandBlockOutput`, off.
 *
 * Every station marker is a `say`, and with the rule at its default each one
 * *also* prints an operator-feedback line — so a walk through a hundred
 * stations doubles its own log and the chat box scrolls the sign you were
 * reading off the screen. Worse in v3 than in v2: the detector command block
 * is *repeating*, so an untracked failure would print twenty times a second.
 * The name is the 1.21.9+ one; the old camelCase spelling is silently dropped
 * at this DataVersion.
 */
export const TERRARIUM_GAME_RULES: Readonly<Record<string, boolean | number>> = Object.freeze({
  "minecraft:command_block_output": false,
  // Nothing in the Terrarium grows, burns, melts or wanders, and a review session is
  // long: a frozen world is one that looks the same at the end of it.
  "minecraft:do_daylight_cycle": false,
  "minecraft:do_weather_cycle": false,
  // v3, and load-bearing rather than tidy: in the v2 session ambient animals
  // wandered onto the platforms and stood in the middle of the exhibit being
  // judged. A void platform is a small enough spawn surface that one sheep is
  // half the frame.
  "minecraft:do_mob_spawning": false,
  "minecraft:do_fire_tick": false,
  "minecraft:random_tick_speed": 0,
});

/* -------------------------------------------------------------------------- */
/* the plan                                                                    */
/* -------------------------------------------------------------------------- */

/**
 * What a station is exhibiting.
 *
 * `"multi"` is v2's addition: a station whose content is a whole compiled
 * mini-settlement rather than one generator's output.
 */
export type TerrariumStationKind = "building" | "prop" | "spawn" | "multi";

/** Where a station's exhibit came from — enough to regenerate it exactly. */
export interface TerrariumProvenance {
  readonly kind: TerrariumStationKind;
  /** The registry row this cell belongs to, e.g. `"cottage"`, `"harbour"`. */
  readonly row: string;
  /** Position within the row, west to east. */
  readonly column: number;
  /** The generator family: an archetype name, or a prop name. */
  readonly family: string;
  /** The node path the seed is derived from — the same one the dev world uses. */
  readonly nodePath: string;
  readonly theme?: string;
  readonly roof?: string;
  readonly floors?: number;
  /** Unrotated extents, as the row laid the cell out. */
  readonly size: readonly [number, number, number];
  /** The cell's `seedSalt`, when its row rerolls rather than varies. */
  readonly seedSalt?: string;
  /** Extra generator params the cell carries. */
  readonly params?: Readonly<Record<string, unknown>>;
}

/** An inclusive rectangle of world columns, with the Y its top sits at. */
export interface TerrariumRect {
  readonly x0: number;
  readonly z0: number;
  readonly x1: number;
  readonly z1: number;
  readonly y: number;
}

/** Where a teleport lands, and the command string that gets there. */
export interface TerrariumLanding {
  readonly x: number;
  readonly y: number;
  readonly z: number;
  /** The `tp` argument triple — block centres, so the player lands on the plate. */
  readonly tp: string;
}

/** One station, planned. */
export interface TerrariumStation {
  /** Index in walk order; the spawn station is not in this sequence. */
  readonly index: number;
  readonly id: string;
  readonly kind: TerrariumStationKind;
  readonly grid: { readonly col: number; readonly row: number };
  readonly platform: TerrariumRect;
  readonly landing: TerrariumLanding;
  /** Where the exhibit itself stands; absent on the spawn station. */
  readonly structure?: TerrariumRect;
  /** Station ids the NEXT and PREV buttons go to. */
  readonly next: string;
  readonly prev: string;
  readonly provenance: TerrariumProvenance;
  /** The mini-settlement this station exhibits; present only on a `multi` one. */
  readonly multi?: TerrariumMulti;
}

/** A multi-structure station's mini-settlement, as the plan knows it. */
export interface TerrariumMulti {
  readonly kind: MultiStationKind;
  readonly title: string;
  readonly question: string;
  /** The mini-document's own name, and the seed it was compiled under. */
  readonly document: string;
  readonly worldSeed: number;
  /**
   * The columns the transplanted settlement occupies, in Terrarium world space.
   *
   * Equal to the compiled region translated by
   * {@link TerrariumMulti.offset}; the apron the machinery stands on is south
   * of it and belongs to the platform, not to the settlement.
   */
  readonly region: TerrariumRect;
  /** What was added to every compiled coordinate to get here. */
  readonly offset: { readonly x: number; readonly z: number };
}

/** The whole Terrarium, before anything is built. */
export interface TerrariumPlan {
  readonly spawn: TerrariumStation;
  readonly stations: readonly TerrariumStation[];
  /** Just the single-structure stations, in walk order. */
  readonly singles: readonly TerrariumStation[];
  /** Just the multi-structure stations, in walk order — the v2 band. */
  readonly multi: readonly TerrariumStation[];
  /** Columns spanned by every platform, for the column plan's region. */
  readonly region: { readonly x0: number; readonly z0: number; readonly width: number; readonly depth: number };
  readonly columns: number;
}

/** One exhibit as the rig sees it, before it is given a platform. */
interface TerrariumCell {
  readonly id: string;
  readonly kind: "building" | "prop";
  /** Extents on the ground the platform has to fit, already rotated. */
  readonly footprint: readonly [number, number];
  readonly provenance: TerrariumProvenance;
  /** The dev-world cell this came from, for the builder. */
  readonly exhibit?: DevExhibit;
  readonly prop?: PropExhibit;
}

/** Rotated ground extents of a prop cell. */
function propExtents(cell: PropExhibit): [number, number] {
  const yaw = (cell.params["yaw"] ?? 0) as StructureYaw;
  const [w, , d] = cell.size;
  return yaw === 90 || yaw === 270 ? [d, w] : [w, d];
}

/**
 * Every exhibit in the registry, in station order.
 *
 * Read from the dev world's own planner rather than from the row files
 * directly, so a row added to the dev world shows up here without this file
 * being touched — the same argument that made `EXTRA_EXHIBIT_ROWS` a seam.
 * The context strips are excluded: a context cell is a building *and its
 * ground*, and putting one on a flat platform would exhibit neither.
 */
export function terrariumCells(): readonly TerrariumCell[] {
  const cells: TerrariumCell[] = [];
  for (const e of planDevGrid().exhibits) {
    cells.push({
      id: `${e.row}__${e.id}`,
      kind: "building",
      footprint: [e.size[0], e.size[2]],
      exhibit: e,
      provenance: {
        kind: "building",
        row: e.row,
        column: e.column,
        family: e.archetype,
        nodePath: `rig.${e.row}.${e.id}`,
        theme: e.theme,
        roof: e.roof,
        floors: e.floors,
        size: e.size,
        ...(e.seedSalt === undefined ? {} : { seedSalt: e.seedSalt }),
        ...(e.params === undefined ? {} : { params: e.params }),
      },
    });
  }
  for (const p of planPropExhibits().exhibits) {
    cells.push({
      id: `prop_${p.row}__${p.id}`,
      kind: "prop",
      footprint: propExtents(p),
      prop: p,
      provenance: {
        kind: "prop",
        row: p.row,
        column: p.column,
        family: p.prop,
        nodePath: `rig.props.${p.row}.${p.id}`,
        theme: p.theme,
        size: p.size,
        params: p.params,
      },
    });
  }
  return cells;
}

/** Platform extents for a cell's ground footprint. */
function platformSize(footprint: readonly [number, number]): [number, number] {
  const width = Math.max(footprint[0] + TERRARIUM_MARGIN * 2, TERRARIUM_MIN_WIDTH);
  const depth = footprint[1] + TERRARIUM_MARGIN * 2 + TERRARIUM_APRON;
  return [width, depth];
}

/** Block-centre coordinates for a `tp` argument triple. */
function tpTriple(x: number, y: number, z: number): string {
  return `${x + 0.5} ${y} ${z + 0.5}`;
}

/**
 * Lay every station out.
 *
 * A square-ish grid on a uniform pitch, in registry order, reading west to
 * east and then south — so "station 40" is somewhere you can find by walking,
 * and NEXT follows the same order the manifest does. Platforms are sized per
 * station and left-aligned in their cell, because a uniform platform big
 * enough for the widest exhibit would put a cottage in the middle of an acre.
 *
 * The multi-structure stations get a **band of their own**, south of the grid
 * and laid west to east on a per-station pitch. Two reasons, both practical:
 * their platforms are three to eight times the width of a cottage's, so folding
 * them into the uniform grid pitch would spread a hundred and fifty single
 * stations over eight times the ground for no gain; and keeping the grid's
 * geometry untouched means a v1 station is at the same coordinates it was, so a
 * screenshot from an earlier session still lines up with the world.
 *
 * Node paths keep their `rig.` prefix deliberately. They are seed material —
 * `nodeSeed(worldSeed, nodePath)` is what picks an exhibit's theme and
 * materials — so renaming them would silently reroll every single-structure
 * station's appearance, which is exactly the kind of unexplained diff the
 * Terrarium exists to make impossible.
 */
export function planTerrarium(): TerrariumPlan {
  const cells = terrariumCells();
  const sizes = cells.map((c) => platformSize(c.footprint));
  const spawnSize: [number, number] = [TERRARIUM_MIN_WIDTH, TERRARIUM_MIN_WIDTH + TERRARIUM_APRON];

  const pitchX = Math.max(spawnSize[0], ...sizes.map((s) => s[0])) + TERRARIUM_GAP;
  const pitchZ = Math.max(spawnSize[1], ...sizes.map((s) => s[1])) + TERRARIUM_GAP;
  // The spawn platform takes the first grid cell, so the walk starts where the
  // player does and the numbering of the stations still starts at one.
  const cols = Math.ceil(Math.sqrt(cells.length + 1));

  const place = (slot: number, size: readonly [number, number]) => {
    const col = slot % cols;
    const row = Math.floor(slot / cols);
    const x0 = col * pitchX;
    const z0 = row * pitchZ;
    const platform: TerrariumRect = {
      x0,
      z0,
      x1: x0 + size[0] - 1,
      z1: z0 + size[1] - 1,
      y: TERRARIUM_GROUND_Y,
    };
    const cx = x0 + (size[0] >> 1);
    const cz = z0 + size[1] - 5;
    const landing: TerrariumLanding = {
      x: cx,
      y: TERRARIUM_GROUND_Y + 1,
      z: cz,
      tp: tpTriple(cx, TERRARIUM_GROUND_Y + 1, cz),
    };
    return { col, row, platform, landing };
  };

  const spawnPlaced = place(0, spawnSize);
  const specs = multiStationSpecs();
  // Walk order, and so the ids NEXT and PREV chase: the grid first, the band
  // after it. Computed before the stations themselves, because a station has to
  // name its neighbours and the last single's neighbour is the first multi.
  const order = [...cells.map((c) => c.id), ...specs.map((s) => s.id)];
  const neighbour = (i: number, step: number): string =>
    order[(i + step + order.length) % order.length] as string;

  const singles: TerrariumStation[] = cells.map((cell, i) => {
    const size = sizes[i] as [number, number];
    const p = place(i + 1, size);
    const sw = cell.footprint[0];
    const sd = cell.footprint[1];
    const sx = p.platform.x0 + ((size[0] - sw) >> 1);
    const sz = p.platform.z0 + TERRARIUM_MARGIN;
    return {
      index: i,
      id: cell.id,
      kind: cell.kind,
      grid: { col: p.col, row: p.row },
      platform: p.platform,
      landing: p.landing,
      structure: { x0: sx, z0: sz, x1: sx + sw - 1, z1: sz + sd - 1, y: TERRARIUM_GROUND_Y },
      // Wrapping, at both ends: a reviewer who overshoots the last station
      // should arrive at the first, not walk off the end of the world.
      next: neighbour(i, 1),
      prev: neighbour(i, -1),
      provenance: cell.provenance,
    };
  });

  // --- the multi band ------------------------------------------------------
  // One row, south of the grid. A platform is its settlement's region, a margin
  // ring, and the apron the machinery stands on. The ring is not decoration:
  // the layout solver will happily put a building hard against the region's
  // edge, and a gable overhang or a porch lamp then lands a block or two
  // outside it. Without ground under those columns they would be blocks in the
  // void — which is a lint failure, and worse, looks like a broken generator.
  const gridRows = Math.ceil((cells.length + 1) / cols);
  const bandZ0 = gridRows * pitchZ + TERRARIUM_BAND_GAP;
  let bandX = 0;
  const multi: TerrariumStation[] = specs.map((spec, k) => {
    const i = cells.length + k;
    const [w, d] = spec.size;
    const x0 = bandX + TERRARIUM_MARGIN;
    const z0 = bandZ0 + TERRARIUM_MARGIN;
    const platform: TerrariumRect = {
      x0: bandX,
      z0: bandZ0,
      x1: x0 + w - 1 + TERRARIUM_MARGIN,
      z1: z0 + d - 1 + TERRARIUM_MARGIN + TERRARIUM_APRON,
      y: TERRARIUM_GROUND_Y,
    };
    bandX = platform.x1 + 1 + TERRARIUM_GAP;
    const cx = platform.x0 + ((platform.x1 - platform.x0 + 1) >> 1);
    const cz = platform.z1 - 4;
    const region: TerrariumRect = { x0, z0, x1: x0 + w - 1, z1: z0 + d - 1, y: TERRARIUM_GROUND_Y };
    return {
      index: i,
      id: spec.id,
      kind: "multi" as const,
      grid: { col: k, row: gridRows },
      platform,
      landing: {
        x: cx,
        y: TERRARIUM_GROUND_Y + 1,
        z: cz,
        tp: tpTriple(cx, TERRARIUM_GROUND_Y + 1, cz),
      },
      structure: region,
      next: neighbour(i, 1),
      prev: neighbour(i, -1),
      provenance: multiProvenance(spec, k),
      multi: {
        kind: spec.kind,
        title: spec.title,
        question: spec.question,
        document: spec.document.meta.name,
        worldSeed: spec.document.meta.worldSeed as number,
        region,
        // `centeredRegion` puts a compiled document's region at
        // `(-floor(w/2), -floor(d/2))`, so this is the region's north-west
        // corner in world space minus the same corner in document space.
        offset: { x: x0 + (w >> 1), z: z0 + (d >> 1) },
      },
    };
  });

  const stations = [...singles, ...multi];

  const spawn: TerrariumStation = {
    index: -1,
    id: TERRARIUM_SPAWN_ID,
    kind: "spawn",
    grid: { col: spawnPlaced.col, row: spawnPlaced.row },
    platform: spawnPlaced.platform,
    landing: spawnPlaced.landing,
    next: (stations[0] as TerrariumStation).id,
    prev: (stations[stations.length - 1] as TerrariumStation).id,
    provenance: {
      kind: "spawn",
      row: "_start",
      column: 0,
      family: "instructions",
      nodePath: "rig._start",
      size: [spawnSize[0], 1, spawnSize[1]],
    },
  };

  const all = [spawn, ...stations];
  const x0 = Math.min(...all.map((s) => s.platform.x0)) - 2;
  const z0 = Math.min(...all.map((s) => s.platform.z0)) - 2;
  const x1 = Math.max(...all.map((s) => s.platform.x1)) + 2;
  const z1 = Math.max(...all.map((s) => s.platform.z1)) + 2;
  const columns = all.reduce(
    (sum, s) => sum + (s.platform.x1 - s.platform.x0 + 1) * (s.platform.z1 - s.platform.z0 + 1),
    0,
  );

  return {
    spawn,
    stations,
    singles,
    multi,
    region: { x0, z0, width: x1 - x0 + 1, depth: z1 - z0 + 1 },
    columns,
  };
}

/**
 * A multi-station's provenance.
 *
 * The single-structure fields are filled in with what a *document* has instead
 * of what a cell has — the row is the composition's kind, the family is the
 * mini-document's name, and `params` carries the question the station is
 * asking. The per-structure detail lives in the manifest's `structures[]`,
 * which is where it can be listed rather than squeezed into one record.
 */
function multiProvenance(spec: MultiStationSpec, column: number): TerrariumProvenance {
  return {
    kind: "multi",
    row: spec.kind,
    column,
    family: spec.document.meta.name,
    // Not a seed path: a multi-station's content is seeded by its own
    // document's `worldSeed`, and this names the station rather than a
    // generator. It is here because every station has one.
    nodePath: `terrarium.multi.${spec.kind}`,
    size: [spec.size[0], 1, spec.size[1]],
    params: { question: spec.question, worldSeed: spec.document.meta.worldSeed },
  };
}

/* -------------------------------------------------------------------------- */
/* the machinery                                                               */
/* -------------------------------------------------------------------------- */

/** Which way a travel cube goes. */
export type TerrariumCubeDirection = "next" | "prev";

/** A box of world blocks, inclusive on every axis. */
export interface TerrariumBox {
  readonly x0: number;
  readonly y0: number;
  readonly z0: number;
  readonly x1: number;
  readonly y1: number;
  readonly z1: number;
}

/**
 * One travel cube: the region you fly into, the pad that marks it, and the
 * three command blocks buried under the pad that do the work.
 */
export interface TerrariumCube {
  readonly direction: TerrariumCubeDirection;
  /** The station this cube teleports to. */
  readonly target: string;
  /** The 3x3x3 volume of air a player has to enter. */
  readonly region: TerrariumBox;
  /** The marked 3x3 of pad blocks under it, at the platform surface. */
  readonly pad: TerrariumRect;
  /** The block name of the pad, and of its centre column. */
  readonly padBlock: string;
  readonly eyeBlock: string;
  /** The repeating detector's command — success powers the chain behind it. */
  readonly detect: string;
  /** Chain 1: the teleport. */
  readonly teleport: string;
  /** Chain 2: the marker line the harvester joins notes on. */
  readonly marker: string;
  /** Where the three command blocks sit, in chain order. */
  readonly blocks: readonly {
    readonly role: "detect" | "teleport" | "marker";
    readonly x: number;
    readonly y: number;
    readonly z: number;
  }[];
}

/** The machinery a station carries, as blocks and compounds. */
interface Machinery {
  readonly blocks: readonly StructureBlock[];
  readonly entities: readonly BlockEntity[];
}

/**
 * The two travel cubes a station carries, west (PREV) first then east (NEXT).
 *
 * Exported because the manifest↔world test asserts on exactly these strings and
 * these coordinates: the property that matters is that the command block buried
 * on the platform runs the command the manifest says it does, and a test that
 * rebuilt the string from its own template would only be checking itself.
 *
 * The selector appears three times — once to ask whether anyone is standing in
 * the cube, once to move them, once implicitly by the chain being conditional
 * on that move — and is written out identically each time on purpose: a
 * detector and a teleporter that disagree about the region would teleport
 * someone who was never in it.
 */
export function terrariumCubes(
  station: TerrariumStation,
  byId: ReadonlyMap<string, TerrariumStation>,
): TerrariumCube[] {
  const y = TERRARIUM_GROUND_Y;
  const zc = station.landing.z;
  const half = TERRARIUM_CUBE_SIZE >> 1;
  const make = (direction: TerrariumCubeDirection, target: string): TerrariumCube => {
    const cx = station.landing.x + (direction === "next" ? TERRARIUM_CUBE_OFFSET : -TERRARIUM_CUBE_OFFSET);
    const x0 = cx - half;
    const z0 = zc - half;
    const x1 = x0 + TERRARIUM_CUBE_SIZE - 1;
    const z1 = z0 + TERRARIUM_CUBE_SIZE - 1;
    // `dx=2` spans three columns, not two: the volume runs from `x` to
    // `x + dx + 1` exclusive. Getting this wrong makes a cube you can fly
    // through the far edge of without being seen.
    const span = TERRARIUM_CUBE_SIZE - 1;
    const selector = `@a[x=${x0},y=${y + 1},z=${z0},dx=${span},dy=${span},dz=${span}]`;
    const landing = (byId.get(target) as TerrariumStation).landing.tp;
    return {
      direction,
      target,
      region: { x0, y0: y + 1, z0, x1, y1: y + TERRARIUM_CUBE_SIZE, z1 },
      pad: { x0, z0, x1, z1, y },
      padBlock: TERRARIUM_CUBE_PADS[direction] as string,
      eyeBlock: TERRARIUM_CUBE_EYES[direction] as string,
      detect: `execute if entity ${selector}`,
      teleport: `tp ${selector} ${landing}`,
      marker: terrariumArrivalCommand(byId.get(target) as TerrariumStation),
      blocks: [
        { role: "detect", x: x0, y: y - 1, z: zc },
        { role: "teleport", x: x0 + 1, y: y - 1, z: zc },
        { role: "marker", x: x0 + 2, y: y - 1, z: zc },
      ],
    };
  };
  return [make("prev", station.prev), make("next", station.next)];
}

/** The command the arrival plate's command block runs. */
export function terrariumArrivalCommand(station: TerrariumStation): string {
  return `say >> STATION ${station.id}`;
}

/**
 * The two label signs a station carries, as their four lines each.
 *
 * One says what the station *is* — its id and its place in the registry — and
 * one says what the generator was *told*, which is the pair a reviewer needs
 * to turn "this roof is wrong" into a reproducible complaint.
 *
 * A multi-station's second sign says the *question* instead of the parameters.
 * There is no single generator config to quote — the provenance is a whole
 * document, which is in the manifest and cannot fit on a sign — and a reviewer
 * standing in front of a compiled hamlet needs to be told which of the dozen
 * things in frame the verdict is about.
 */
export function terrariumSignLines(station: TerrariumStation): [string[], string[]] {
  const p = station.provenance;
  if (station.kind === "spawn") {
    return [
      ["TERRARIUM", "", "fly into LIME", "to go forward"],
      ["RED goes back", "", "type in chat to", "leave a note"],
    ];
  }
  const multi = station.multi;
  if (multi !== undefined) {
    return [
      [`#${station.index + 1} ${multi.kind}`, truncate(multi.title, 15), multi.document, `seed ${multi.worldSeed}`],
      ["JUDGE THIS:", ...wrapSign(multi.question, 3)],
    ];
  }
  const size = `${p.size[0]}x${p.size[1]}x${p.size[2]}`;
  const extras = Object.keys(p.params ?? {}).join(" ");
  return [
    [`#${station.index + 1} ${p.row}`, truncate(station.id, 15), p.family, `col ${p.column}`],
    [
      `size ${size}`,
      p.roof === undefined ? `theme ${p.theme ?? "-"}` : `roof ${p.roof} f${p.floors ?? 1}`,
      p.roof === undefined ? extras : `theme ${p.theme ?? "-"}`,
      p.seedSalt === undefined ? extras : `salt ${p.seedSalt}`,
    ],
  ];
}

/** The four instruction signs on the spawn platform. */
const TERRARIUM_INSTRUCTIONS: readonly (readonly string[])[] = Object.freeze([
  ["HOW THIS WORKS", "1. fly into the", "   LIME pad to", "   go forward"],
  ["2. RED pad goes", "   back one", "3. look at the", "   one exhibit"],
  ["4. say anything", "in chat, verdict", "included: it is", "recorded here"],
  ["you are a", "spectator: fly", "through walls,", "touch nothing"],
]);

function truncate(text: string, max: number): string {
  return text.length <= max ? text : `${text.slice(0, max - 1)}~`;
}

/**
 * Break a sentence across a fixed number of sign lines.
 *
 * Greedy, on word boundaries, at the fifteen characters a sign renders before
 * it starts eliding — and always exactly `lines` entries, because a sign
 * compound with three lines where four were expected renders the missing one
 * as the literal string `null` in game.
 */
function wrapSign(text: string, lines: number): string[] {
  const out: string[] = [];
  let current = "";
  for (const word of text.split(/\s+/)) {
    const candidate = current === "" ? word : `${current} ${word}`;
    if (candidate.length <= 15 || current === "") {
      current = candidate;
      continue;
    }
    out.push(current);
    current = word;
  }
  if (current !== "") out.push(current);
  while (out.length < lines) out.push("");
  return out.slice(0, lines);
}

/**
 * Build one station's machinery.
 *
 * The geometry is fixed relative to the landing spot, which is what makes the
 * rig navigable: the signs are always at the same two offsets, the lime pad is
 * always six columns east and the red one always six columns west, and a
 * reviewer who has done one station has done all of them.
 */
function buildMachinery(
  station: TerrariumStation,
  cubes: readonly TerrariumCube[],
  stack: PrismarineStack,
): Machinery {
  const blocks: StructureBlock[] = [];
  const entities: BlockEntity[] = [];
  const y = TERRARIUM_GROUND_Y;
  const state = (name: string, props?: Record<string, string>): number =>
    (props === undefined ? stack.blockByName(name)?.stateId : stack.blockStateOf(name, props)) ?? 0;

  const cx = station.landing.x;
  const zLand = station.landing.z;

  // --- the arrival plate, on its command block ------------------------------
  // The plate strongly powers the block beneath it, so an impulse command
  // block directly under the landing spot fires once per arrival — which is
  // exactly the granularity the log harvester wants.
  blocks.push({ x: cx, y, z: zLand, stateId: state("command_block", { conditional: "false", facing: "up" }) });
  blocks.push({
    x: cx,
    y: y + 1,
    z: zLand,
    stateId: state("stone_pressure_plate", { powered: "false" }),
  });
  entities.push(
    commandBlockEntity(cx, y, zLand, terrariumArrivalCommand(station), {
      auto: false,
      trackOutput: false,
      customName: "@",
    }),
  );

  // --- the label signs -----------------------------------------------------
  // Standing signs on the platform, one either side of the plate, facing south
  // so they read from the spot the player lands on.
  const [lineA, lineB] = terrariumSignLines(station);
  const signState = state("oak_sign", { rotation: "0", waterlogged: "false" });
  for (const [dx, lines] of [
    [-2, lineA],
    [2, lineB],
  ] as const) {
    blocks.push({ x: cx + dx, y: y + 1, z: zLand - 1, stateId: signState });
    entities.push(signEntity(cx + dx, y + 1, zLand - 1, { front: lines, waxed: true }));
  }

  // --- the spawn platform's instructions -----------------------------------
  if (station.kind === "spawn") {
    for (const [i, lines] of TERRARIUM_INSTRUCTIONS.entries()) {
      const x = cx - 3 + i * 2;
      blocks.push({ x, y: y + 1, z: zLand - 3, stateId: signState });
      entities.push(signEntity(x, y + 1, zLand - 3, { front: lines, waxed: true }));
    }
  }

  // --- the travel cubes ----------------------------------------------------
  // A marked 3x3 pad at the platform surface, the 3x3x3 of air above it left
  // alone, and the chain buried one course under the pad where it cannot be
  // seen, stood on, or broken. The chain runs west to east: the repeating
  // detector faces east into the first conditional chain block, which faces
  // east into the second — so a chain block only runs when the block behind it
  // succeeded, which is what makes "teleport, then announce" one atomic thing.
  for (const cube of cubes) {
    for (let x = cube.pad.x0; x <= cube.pad.x1; x++) {
      for (let z = cube.pad.z0; z <= cube.pad.z1; z++) {
        const eye = x === cube.pad.x0 + 1 && z === cube.pad.z0 + 1;
        blocks.push({
          x,
          y,
          z,
          stateId: eye ? state(cube.eyeBlock, { facing: "north" }) : state(cube.padBlock),
        });
      }
    }
    // Air, explicitly: the substrate put a surface block at `y` and nothing
    // above it, but a prop or a snow layer could have reached in, and a cube
    // with a block in it is a cube a creative-mode reviewer bounces off.
    for (let dy = 0; dy < TERRARIUM_CUBE_SIZE; dy++) {
      for (let x = cube.region.x0; x <= cube.region.x1; x++) {
        for (let z = cube.region.z0; z <= cube.region.z1; z++) {
          blocks.push({ x, y: y + 1 + dy, z, stateId: state("air") });
        }
      }
    }
    const commands: Record<string, string> = {
      detect: cube.detect,
      teleport: cube.teleport,
      marker: cube.marker,
    };
    for (const slot of cube.blocks) {
      const name = slot.role === "detect" ? "repeating_command_block" : "chain_command_block";
      blocks.push({
        x: slot.x,
        y: slot.y,
        z: slot.z,
        stateId: state(name, {
          conditional: slot.role === "detect" ? "false" : "true",
          facing: "east",
        }),
      });
      entities.push(
        // `auto` — "always active" — rather than redstone-powered: there is no
        // redstone down here, and a detector that needs a button defeats the
        // point of a mechanism a spectator can trigger.
        commandBlockEntity(slot.x, slot.y, slot.z, commands[slot.role] as string, {
          auto: true,
          trackOutput: false,
          customName: "@",
        }),
      );
    }
  }

  return { blocks, entities };
}

/* -------------------------------------------------------------------------- */
/* the build                                                                   */
/* -------------------------------------------------------------------------- */

/** The door port every exhibit declares — the same one the dev world uses. */
const TERRARIUM_PORTS: Readonly<Record<string, PortDeclaration>> = Object.freeze({
  door: { type: "door", face: "south", tags: ["primary"] } as PortDeclaration,
});

/** What {@link buildTerrarium} produced. */
export interface TerrariumResult {
  readonly plan: TerrariumPlan;
  readonly manifest: TerrariumManifest;
  readonly worldDir: string;
  readonly manifestPath: string;
  readonly levelDatPath: string;
  readonly regionFiles: readonly string[];
  readonly chunkCount: number;
  readonly blockCount: number;
  /** Columns dug and flooded for the harbour stations' basins. */
  readonly pondColumns: number;
  readonly blockEntityCount: number;
  readonly stationCount: number;
  /** Of those, the v2 multi-structure ones. */
  readonly multiStationCount: number;
  /**
   * Every building in the world, single-structure exhibits and transplanted
   * settlements alike, in world coordinates — the physics lint's context.
   */
  readonly buildings: readonly BuiltBuilding[];
  readonly placedProps: readonly PlacedProp[];
  /** Tunnel endpoints, translated: the traversal lint walks between them. */
  readonly tunnels: readonly TunnelLandmark[];
  /** Road centre lines, translated, for the flush-road rule. */
  readonly roads: readonly { readonly path: readonly { readonly x: number; readonly z: number; readonly y: number }[] }[];
  /** Every block the generators and the machinery emitted, in build order. */
  readonly structureBlocks: readonly StructureBlock[];
  readonly entities: readonly BlockEntity[];
  readonly connections: ConnectionStats;
  readonly minecraftVersion: string;
  readonly dataVersion: number;
  /** Each multi-station's compile output, keyed by station id. */
  readonly compiled: ReadonlyMap<string, CompiledMiniStation>;
}

/** A tunnel as the physics lint wants it: two cells that must be joined. */
export interface TunnelLandmark {
  readonly id: string;
  readonly from: { readonly x: number; readonly y: number; readonly z: number };
  readonly to: { readonly x: number; readonly y: number; readonly z: number };
}

/** Translate a built building into Terrarium world space. */
function shiftBuilding(b: BuiltBuilding, dx: number, dz: number): BuiltBuilding {
  const rect = (r: { x0: number; z0: number; x1: number; z1: number }) => ({
    x0: r.x0 + dx,
    z0: r.z0 + dz,
    x1: r.x1 + dx,
    z1: r.z1 + dz,
  });
  const cells = (set: ReadonlySet<string>): Set<string> => {
    const out = new Set<string>();
    for (const key of set) {
      const comma = key.indexOf(",");
      out.add(`${Number(key.slice(0, comma)) + dx},${Number(key.slice(comma + 1)) + dz}`);
    }
    return out;
  };
  return {
    ...b,
    footprint: rect(b.footprint),
    interior: rect(b.interior),
    cells: cells(b.cells),
    ...(b.interiorCells === undefined ? {} : { interiorCells: cells(b.interiorCells) }),
    ...(b.basementInterior === undefined ? {} : { basementInterior: rect(b.basementInterior) }),
    ...(b.basementCells === undefined ? {} : { basementCells: cells(b.basementCells) }),
  };
}

/** The manifest format string this build writes. */
export const TERRARIUM_MANIFEST_FORMAT = "terrainist-terrarium/2";

/** The v1 format string, still accepted by the harvester. */
export const TERRARIUM_MANIFEST_FORMAT_V1 = "terrainist-review-rig/1";

/** The manifest, as written next to the world. */
export interface TerrariumManifest {
  readonly format: typeof TERRARIUM_MANIFEST_FORMAT;
  readonly world: string;
  readonly minecraftVersion: string;
  readonly dataVersion: number;
  readonly worldSeed: string;
  readonly groundY: number;
  readonly gameRules: Readonly<Record<string, boolean | number>>;
  readonly stationCount: number;
  /** Of those, the v2 multi-structure ones. */
  readonly multiStationCount: number;
  readonly spawn: TerrariumManifestStation;
  readonly stations: readonly TerrariumManifestStation[];
  /**
   * The checkout that built this world, when the caller supplied it.
   *
   * Additive and optional, so no format bump: a v2 reader that has never heard
   * of the field ignores it, and one that wants it finds it. It exists so a
   * review session held a week later can be joined back to the exact commit —
   * and can tell a `baseline` build from a nightly one.
   */
  readonly provenance?: Provenance;
}

/**
 * One structure inside a multi-station's settlement.
 *
 * The point of the list is joinability: a reviewer's "the inn's roof is wrong"
 * has to reach the node that produced the inn, and the only durable handle on
 * that node is its path in the mini-document. Attribution is still recorded per
 * *station* — the harvester has no way to tell which of five buildings a chat
 * line was about — so this is what a human (or a later pass) reads to turn one
 * station-level note into a specific edit. **Per-structure attribution is v3.**
 */
export interface TerrariumStructure {
  /** Path inside the mini-document, e.g. `"world.inn"`. */
  readonly nodePath: string;
  /** The node's own id. */
  readonly id: string;
  readonly generator: string;
  /** What the document asked for, verbatim. */
  readonly provenance: {
    readonly label?: string;
    readonly params?: Readonly<Record<string, unknown>>;
    readonly tags?: readonly string[];
    /** Where it ended up, in Terrarium world columns. */
    readonly footprint?: { readonly x0: number; readonly z0: number; readonly x1: number; readonly z1: number };
    /** Walkable ground floor, in world Y; buildings only. */
    readonly floorY?: number;
    /** Cellar plane, in world Y; buildings with a basement only. */
    readonly basementFloorY?: number;
    /** Centre-line length in columns; roads and tunnels only. */
    readonly length?: number;
    /** The two node paths a tunnel joins. */
    readonly joins?: readonly [string, string];
  };
}

/** One station in the manifest — everything needed to join a note back. */
export interface TerrariumManifestStation {
  readonly index: number;
  readonly id: string;
  readonly kind: TerrariumStationKind;
  readonly grid: { readonly col: number; readonly row: number };
  readonly platform: TerrariumRect;
  readonly landing: TerrariumLanding;
  readonly structure?: TerrariumRect;
  readonly next: string;
  readonly prev: string;
  /** The commands the station's command blocks carry, by machine role. */
  readonly commands: Readonly<Record<string, string>>;
  /**
   * v3: the two travel cubes beside the landing, PREV then NEXT.
   *
   * Additive, and deliberately not a format bump — the harvester joins on `id`
   * and reads nothing here. It is in the manifest because a cube is the only
   * part of the rig whose *geometry* is a contract: a later tool that wants to
   * check "did the reviewer actually visit station 40" has the region to test
   * against, and a human debugging a dead pad has the three buried coordinates
   * without having to dig.
   */
  readonly cubes?: readonly TerrariumCube[];
  readonly provenance: TerrariumProvenance;
  /** v2, multi-stations only: the composition, and where it was transplanted. */
  readonly multi?: TerrariumMulti;
  /** v2, multi-stations only: every structure the pipeline placed. */
  readonly structures?: readonly TerrariumStructure[];
  /**
   * v2, multi-stations only: the mini-document, inline and verbatim.
   *
   * Inline rather than a path, because the join has to survive the world folder
   * being zipped, installed, walked a week later and reviewed against a
   * checkout that has moved on. The document *is* the generating configuration;
   * a reference to one would be a promise that a file still says what it said.
   */
  readonly document?: unknown;
}

/**
 * The manifest for a plan.
 *
 * Pure with respect to the plan, so a test can build it without a world; the
 * per-structure lists come from the compiled mini-stations and are simply
 * absent when the caller has none (which is the planning-only case).
 */
export function terrariumManifest(
  plan: TerrariumPlan,
  stack: PrismarineStack,
  compiled?: ReadonlyMap<string, CompiledMiniStation>,
  provenance?: Provenance,
): TerrariumManifest {
  const byId = stationIndex(plan);
  const entry = (s: TerrariumStation): TerrariumManifestStation => {
    const commands: Record<string, string> = { arrive: terrariumArrivalCommand(s) };
    const cubes = terrariumCubes(s, byId);
    for (const cube of cubes) commands[cube.direction] = cube.teleport;
    const mini = compiled?.get(s.id);
    return {
      index: s.index,
      id: s.id,
      kind: s.kind,
      grid: s.grid,
      platform: s.platform,
      landing: s.landing,
      ...(s.structure === undefined ? {} : { structure: s.structure }),
      next: s.next,
      prev: s.prev,
      commands,
      cubes,
      provenance: s.provenance,
      ...(s.multi === undefined ? {} : { multi: s.multi }),
      ...(mini === undefined
        ? {}
        : {
            structures: miniStructures(mini, s.multi as TerrariumMulti),
            document: mini.spec.document,
          }),
    };
  };
  return {
    format: TERRARIUM_MANIFEST_FORMAT,
    world: TERRARIUM_WORLD_NAME,
    minecraftVersion: stack.minecraftVersion,
    dataVersion: stack.dataVersion,
    worldSeed: TERRARIUM_WORLD_SEED.toString(),
    groundY: TERRARIUM_GROUND_Y,
    gameRules: TERRARIUM_GAME_RULES,
    stationCount: plan.stations.length,
    multiStationCount: plan.multi.length,
    spawn: entry(plan.spawn),
    stations: plan.stations.map(entry),
    ...(provenance === undefined ? {} : { provenance }),
  };
}

/**
 * Every structure one compiled mini-station placed, in a stable order.
 *
 * Buildings and plaza/props first, in the layout solver's document order, then
 * roads and tunnels — which are relations between the things above them and
 * read better after their endpoints have been named.
 */
function miniStructures(mini: CompiledMiniStation, multi: TerrariumMulti): TerrariumStructure[] {
  const { x, z } = multi.offset;
  const doc = mini.spec.document as unknown as {
    root: { id: string; children: readonly Record<string, unknown>[] };
  };
  const nodeById = new Map(doc.root.children.map((c) => [c["id"] as string, c] as const));
  const shift = (r: { x0: number; z0: number; x1: number; z1: number }) => ({
    x0: r.x0 + x,
    z0: r.z0 + z,
    x1: r.x1 + x,
    z1: r.z1 + z,
  });
  const idOf = (nodePath: string): string => nodePath.slice(nodePath.lastIndexOf(".") + 1);
  const base = (nodePath: string) => {
    const node = nodeById.get(idOf(nodePath));
    return {
      ...(node?.["label"] === undefined ? {} : { label: node["label"] as string }),
      ...(node?.["params"] === undefined
        ? {}
        : { params: node["params"] as Readonly<Record<string, unknown>> }),
      ...(node?.["tags"] === undefined ? {} : { tags: node["tags"] as readonly string[] }),
    };
  };

  const out: TerrariumStructure[] = [];
  const seen = new Set<string>();
  for (const building of mini.buildings) {
    seen.add(building.nodePath);
    out.push({
      nodePath: building.nodePath,
      id: idOf(building.nodePath),
      generator: "building.grammar@0",
      provenance: {
        ...base(building.nodePath),
        footprint: shift(building.footprint),
        floorY: building.floorY,
        ...(building.basementFloorY === undefined
          ? {}
          : { basementFloorY: building.basementFloorY }),
      },
    });
  }
  for (const prop of mini.props) {
    seen.add(prop.nodePath);
    out.push({
      nodePath: prop.nodePath,
      id: idOf(prop.nodePath),
      generator: "prop.place@0",
      provenance: { ...base(prop.nodePath), footprint: shift(prop.footprint) },
    });
  }
  // Whatever the solver placed that produced no geometry of its own — the
  // plaza primitive, most of all. It is a structure a reviewer can see and so
  // one a note can be about.
  for (const placement of mini.placements) {
    if (seen.has(placement.nodePath)) continue;
    out.push({
      nodePath: placement.nodePath,
      id: idOf(placement.nodePath),
      generator: placement.generator,
      provenance: base(placement.nodePath),
    });
  }
  for (const route of mini.routes) {
    out.push({
      nodePath: `${doc.root.id}.${route.from}->${route.to}`,
      id: `${route.from}->${route.to}`,
      generator: "road.network@0",
      provenance: { length: route.path.length },
    });
  }
  for (const tunnel of mini.tunnels) {
    out.push({
      nodePath: tunnel.id,
      id: idOf(tunnel.id),
      generator: "tunnel",
      provenance: {
        length: tunnel.path.length,
        joins: [tunnel.fromPath, tunnel.toPath] as const,
      },
    });
  }
  return out;
}

/** Every station by id, spawn included. */
export function stationIndex(plan: TerrariumPlan): Map<string, TerrariumStation> {
  const byId = new Map<string, TerrariumStation>();
  byId.set(plan.spawn.id, plan.spawn);
  for (const s of plan.stations) byId.set(s.id, s);
  return byId;
}

/**
 * Build the Terrarium and write it into `outDir/terrarium`, with its manifest
 * alongside.
 */
export async function buildTerrarium(
  outDir: string,
  provenance?: Provenance,
): Promise<TerrariumResult> {
  const stack = loadPrismarine(EMIT_MINECRAFT_VERSION);
  const plan = planTerrarium();
  const byId = stationIndex(plan);
  const cells = terrariumCells();

  // --- the multi-structure stations, compiled ------------------------------
  // Sequential rather than parallel: each compile allocates a column plan and
  // its typed-array fields, and a stable order costs nothing here while making
  // any failure's message point at one document.
  const compiled = new Map<string, CompiledMiniStation>();
  for (const station of plan.multi) {
    const spec = multiStationSpecs().find((s) => s.id === station.id) as MultiStationSpec;
    compiled.set(station.id, await compileMiniStation(spec));
  }

  // The column plan is a *substrate*, not the world: the generators sample it
  // for ground level and material, the pond digger writes into it, and only
  // the columns inside a platform are ever materialized.
  const columnPlan = devColumnPlan(
    { x0: plan.region.x0, z0: plan.region.z0, width: plan.region.width, depth: plan.region.depth },
    stack,
  );

  // --- ponds, before anything stands on them -------------------------------
  // A harbour prop only exists over water, and the placer measures itself
  // against the finished plan, so every basin is dug first. The basin is the
  // station's structure rect grown by the margin, which keeps it clear of the
  // platform edge and so of the machinery.
  // Derived from the plan's own water flags — a name literal here silently
  // beaches every water prop a later row adds (measured: the trireme, dry).
  const waterRows = new Set(PROP_EXHIBIT_PLAN.filter((r) => r.water).map((r) => r.row));
  let pondColumns = 0;
  for (const station of plan.stations) {
    if (station.kind !== "prop" || !waterRows.has(station.provenance.row)) continue;
    const r = station.structure as TerrariumRect;
    pondColumns += digPropPond(
      columnPlan,
      { x0: r.x0 - 2, z0: r.z0 - 2, x1: r.x1 + 2, z1: r.z1 + 2 },
      stack,
    );
  }

  // --- the exhibits --------------------------------------------------------
  const buildingJobs: BuildingJob[] = [];
  const propJobs: PropJob[] = [];
  for (const [i, cell] of cells.entries()) {
    const station = plan.singles[i] as TerrariumStation;
    const rect = station.structure as TerrariumRect;
    const nodePath = cell.provenance.nodePath;
    if (cell.kind === "building") {
      const e = cell.exhibit as DevExhibit;
      const seed = nodeSeed(TERRARIUM_WORLD_SEED, nodePath, e.seedSalt ?? "");
      const theme = pickTheme(seed, e.theme);
      const materials = assignMaterials(theme, 1, seed)[0] as BuildingMaterials;
      buildingJobs.push({
        nodePath,
        placement: {
          nodePath,
          id: station.id,
          translation: [rect.x0, TERRARIUM_GROUND_Y, rect.z0] as [number, number, number],
          yaw: 0,
          mirror: false,
          size: e.size,
          footprint: { x0: rect.x0, z0: rect.z0, x1: rect.x1, z1: rect.z1 },
          anchor: { x: rect.x0 + ((e.size[0] - 1) >> 1), z: rect.z0 + ((e.size[2] - 1) >> 1) },
          foundationY: TERRARIUM_GROUND_Y,
        },
        size: e.size,
        params: exhibitParams(e),
        ports: TERRARIUM_PORTS,
        seed,
        tags: [e.archetype],
        materials,
      });
    } else {
      const p = cell.prop as PropExhibit;
      const seed = nodeSeed(TERRARIUM_WORLD_SEED, nodePath, "");
      const theme = pickTheme(seed, p.theme);
      const materials = assignMaterials(theme, 1, seed)[0] as BuildingMaterials;
      propJobs.push({
        nodePath,
        prop: p.prop,
        params: { ...p.params, at: { x: rect.x0, z: rect.z0 } },
        seed,
        materials,
      });
    }
  }

  const built = buildBuildings(buildingJobs, columnPlan, stack);
  const props = buildProps({ jobs: propJobs, plan: columnPlan, stack });

  // --- the machinery -------------------------------------------------------
  const machineryBlocks: StructureBlock[] = [];
  const entities: BlockEntity[] = [];
  for (const station of [plan.spawn, ...plan.stations]) {
    const m = buildMachinery(station, terrariumCubes(station, byId), stack);
    machineryBlocks.push(...m.blocks);
    entities.push(...m.entities);
  }

  // --- the transplants -----------------------------------------------------
  // Each compiled settlement's blocks, translated into its platform. Decor
  // first and structures after, the same order the terrain emitter uses, so a
  // wall always wins over a tuft of grass that shared its column.
  const transplanted: StructureBlock[] = [];
  const transplantedBuildings: BuiltBuilding[] = [];
  const transplantedProps: PlacedProp[] = [];
  const transplantedTunnels: TunnelLandmark[] = [];
  const transplantedRoads: { path: readonly { x: number; z: number; y: number }[] }[] = [];
  for (const station of plan.multi) {
    const mini = compiled.get(station.id) as CompiledMiniStation;
    const { x: dx, z: dz } = (station.multi as TerrariumMulti).offset;
    // Clipped to the platform, and to the platform only. A block whose column
    // is not on the platform has nothing under it, and a lamp post standing in
    // the void reads as a defect in the generator rather than in the mount.
    const p = station.platform;
    const keep = (x: number, z: number): boolean => x >= p.x0 && x <= p.x1 && z >= p.z0 && z <= p.z1;
    for (const b of [...mini.artifacts.decor, ...(mini.artifacts.structures ?? [])]) {
      if (!keep(b.x + dx, b.z + dz)) continue;
      transplanted.push({ x: b.x + dx, y: b.y, z: b.z + dz, stateId: b.stateId });
    }
    for (const b of mini.buildings) transplantedBuildings.push(shiftBuilding(b, dx, dz));
    for (const p of mini.props) {
      transplantedProps.push({
        ...p,
        footprint: {
          x0: p.footprint.x0 + dx,
          z0: p.footprint.z0 + dz,
          x1: p.footprint.x1 + dx,
          z1: p.footprint.z1 + dz,
        },
      });
    }
    for (const t of mini.tunnels) {
      transplantedTunnels.push({
        id: t.id,
        from: { x: t.endpoints[0].x + dx, y: t.endpoints[0].y, z: t.endpoints[0].z + dz },
        to: { x: t.endpoints[1].x + dx, y: t.endpoints[1].y, z: t.endpoints[1].z + dz },
      });
    }
    for (const r of mini.routes) {
      transplantedRoads.push({ path: r.path.map((c) => ({ x: c.x + dx, z: c.z + dz, y: c.y })) });
    }
  }

  // --- materialize ---------------------------------------------------------
  const structureBlocks = [...built.blocks, ...props.blocks, ...transplanted, ...machineryBlocks];
  const chunks = new Map<string, EmitChunk>();
  const chunkFor = (cx: number, cz: number): EmitChunk => {
    const key = `${cx},${cz}`;
    let chunk = chunks.get(key);
    if (chunk === undefined) {
      chunk = stack.createChunk();
      // One biome for the whole world, including over a transplanted
      // settlement. Biome is grass tint and water tint and nothing a reviewer
      // is being asked about, and a chunk that straddles two platforms can
      // only have one — so it is the substrate's, everywhere, rather than a
      // seam that moves when a station is resized.
      paintChunkBiome(chunk, columnPlan.biome[0] as number);
      chunks.set(key, chunk);
    }
    return chunk;
  };

  let blockCount = 0;
  for (const station of [plan.spawn, ...plan.stations]) {
    if (station.multi === undefined) {
      blockCount += materializeColumns(chunkFor, columnPlan, station.platform);
      continue;
    }
    // A multi-station's platform is its settlement's columns, a margin ring and
    // the apron. The settlement's columns come from its own compiled plan; the
    // surround comes from the flat substrate, which agrees with the
    // mini-document's `baseHeight` by construction, so the two meet flush — and
    // that is exactly why every mini-document's *rim* is flat even when its
    // middle is not.
    const region = station.multi.region;
    const p = station.platform;
    const mini = compiled.get(station.id) as CompiledMiniStation;
    blockCount += materializeColumns(chunkFor, mini.artifacts.plan, region, station.multi.offset);
    const y = TERRARIUM_GROUND_Y;
    for (const strip of [
      { x0: p.x0, z0: p.z0, x1: p.x1, z1: region.z0 - 1, y },
      { x0: p.x0, z0: region.z1 + 1, x1: p.x1, z1: p.z1, y },
      { x0: p.x0, z0: region.z0, x1: region.x0 - 1, z1: region.z1, y },
      { x0: region.x1 + 1, z0: region.z0, x1: p.x1, z1: region.z1, y },
    ]) {
      blockCount += materializeColumns(chunkFor, columnPlan, strip);
    }
  }
  for (const block of structureBlocks) {
    if (block.y < WORLD_MIN_Y || block.y > 319) continue;
    const cx = block.x >> 4;
    const cz = block.z >> 4;
    chunkFor(cx, cz).setStateId(block.x - cx * 16, block.y, block.z - cz * 16, block.stateId);
    blockCount++;
  }
  for (const entity of entities) {
    const cx = entity.x >> 4;
    const cz = entity.z >> 4;
    chunkFor(cx, cz).setBlockEntityNbt(entity.x, entity.y, entity.z, {
      ...entity.data,
      id: { type: "string", value: entity.id },
    });
  }

  // Fences, walls and panes store their neighbours in their own state and the
  // game never recomputes it, so the connection pass runs over the finished
  // world exactly as it does for a compiled one.
  const connections = applyConnectionStates(chunks, structureBlocks, stack);

  const worldDir = path.join(path.resolve(outDir), TERRARIUM_WORLD_NAME);
  const written = await writeWorldFiles({
    chunks,
    worldDir,
    levelName: TERRARIUM_WORLD_NAME,
    spawn: { x: plan.spawn.landing.x, y: plan.spawn.landing.y, z: plan.spawn.landing.z },
    stack,
    gameRules: TERRARIUM_GAME_RULES,
    gameType: TERRARIUM_GAME_TYPE,
  });

  const manifest = terrariumManifest(plan, stack, compiled, provenance);
  const manifestPath = path.join(path.resolve(outDir), TERRARIUM_MANIFEST_NAME);
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);

  return {
    plan,
    manifest,
    worldDir: written.worldDir,
    manifestPath,
    levelDatPath: written.levelDatPath,
    regionFiles: written.regionFiles,
    chunkCount: written.chunkCount,
    blockCount,
    pondColumns,
    blockEntityCount: entities.length,
    stationCount: plan.stations.length,
    multiStationCount: plan.multi.length,
    buildings: [...built.built, ...transplantedBuildings],
    placedProps: [...props.placed, ...transplantedProps],
    tunnels: transplantedTunnels,
    roads: transplantedRoads,
    structureBlocks,
    entities,
    connections,
    minecraftVersion: stack.minecraftVersion,
    dataVersion: stack.dataVersion,
    compiled,
  };
}

/**
 * Write one rectangle of a plan's columns into the world.
 *
 * A bounded, floored version of the terrain emitter's column fill: soil and
 * surface exactly as the plan holds them (so a dug basin arrives as sand and
 * water rather than as a hole in the grass), stone from there down to
 * {@link TERRARIUM_PLATFORM_FLOOR}, and nothing at all outside the rectangle. No
 * bedrock: the underside of a platform is meant to be *seen*, and a course of
 * bedrock under every station would read as a floor the world once had.
 *
 * `rect` is in **world** columns and `offset` is what was added to the plan's
 * own coordinates to get there — zero for the substrate, and the platform's
 * displacement for a transplanted settlement. Cave spans are punched last, as
 * `cave_air`, exactly as the emitter does it: a transplanted pair of cellars is
 * joined by a bored gallery, and a fill that ignored the bore would seal it.
 */
function materializeColumns(
  chunkFor: (cx: number, cz: number) => EmitChunk,
  plan: ColumnPlan,
  rect: TerrariumRect,
  offset: { readonly x: number; readonly z: number } = { x: 0, z: 0 },
): number {
  const { region } = plan;
  const stone = plan.states.stone;
  let count = 0;
  for (let z = rect.z0; z <= rect.z1; z++) {
    const j = z - offset.z - region.z0;
    if (j < 0 || j >= region.depth) continue;
    for (let x = rect.x0; x <= rect.x1; x++) {
      const i = x - offset.x - region.x0;
      if (i < 0 || i >= region.width) continue;
      const idx = j * region.width + i;
      const chunk = chunkFor(x >> 4, z >> 4);
      const lx = x - (x >> 4) * 16;
      const lz = z - (z >> 4) * 16;

      const top = plan.ground[idx] as number;
      const soilDepth = plan.soil[idx] as number;
      const soilBase = top - soilDepth;
      if (soilBase - 1 >= TERRARIUM_PLATFORM_FLOOR) {
        chunk.fillColumn(lx, lz, TERRARIUM_PLATFORM_FLOOR, soilBase - 1, stone);
        count += soilBase - TERRARIUM_PLATFORM_FLOOR;
      }
      if (soilDepth > 0 && top - 1 >= soilBase) {
        chunk.fillColumn(lx, lz, soilBase, top - 1, plan.subsurface[idx] as number);
        count += top - soilBase;
      }
      chunk.setStateId(lx, top, lz, plan.surface[idx] as number);
      count += 1;

      const kind = plan.fluidKind[idx];
      if (kind !== FluidKind.NONE) {
        const fluidState = kind === FluidKind.LAVA ? plan.states.lava : plan.states.water;
        const surfaceY = plan.fluidTop[idx] as number;
        if (surfaceY > top) {
          chunk.fillColumn(lx, lz, top + 1, surfaceY, fluidState);
          count += surfaceY - top;
        }
      } else if (plan.snow[idx] === 1 && top + 1 <= 319) {
        chunk.setStateId(lx, top + 1, lz, plan.states.snowLayer);
        count += 1;
      }

      const caves = plan.caves;
      if (caves === undefined) continue;
      const end = caves.spans.offsets[idx + 1] as number;
      for (let k = caves.spans.offsets[idx] as number; k < end; k++) {
        const lo = Math.max(caves.spans.lo[k] as number, TERRARIUM_PLATFORM_FLOOR);
        const hi = caves.spans.hi[k] as number;
        if (hi < lo) continue;
        chunk.fillColumn(lx, lz, lo, hi, plan.states.caveAir);
        count -= hi - lo + 1;
      }
    }
  }
  return count;
}

/** Paint a whole chunk one biome, at the 4×4×4 resolution the format wants. */
function paintChunkBiome(chunk: EmitChunk, biomeId: number): void {
  for (let cellZ = 0; cellZ < 4; cellZ++) {
    for (let cellX = 0; cellX < 4; cellX++) {
      for (let y = WORLD_MIN_Y; y < WORLD_MIN_Y + 384; y += 4) {
        chunk.setBiomeAt(cellX * 4, y, cellZ * 4, biomeId);
      }
    }
  }
}
