import { blake3 } from "@noble/hashes/blake3.js";
import { describe, expect, it } from "vitest";

import { centeredRegion } from "../src/field/index.js";
import { buildTerrainField, type TerrainFieldRequest } from "../src/index.js";

/**
 * The determinism contract, made testable: same spec + same seed → byte-identical
 * field. These hashes are **pinned**. If one of them changes, the change rerolls
 * every world ever generated by this toolchain — so it must be a deliberate,
 * versioned decision, never an accidental consequence of a refactor.
 *
 * ## Reroll log
 *
 * - **G2.5a (organic geometry + hydrology)** — authorized reroll. Radial verbs
 *   gained angular + noise modulation of their extent (`irregularity`, default
 *   0.18), corridor verbs gained meander / width variation / endpoint taper
 *   (`meander`, default 0.5), `river` beds now follow the descent profile
 *   instead of trenching to sea level, and classification took on the ocean
 *   flood-fill (so beaches need actual sea, and landlocked carves stay dry).
 *   Every one of those changes the field by design. Pre-1.0 kernel iteration;
 *   no world in the wild depends on the old hashes.
 * - **G2.5b (materials / lushness)** — authorized reroll of the *compiled
 *   world*, not of the field. Every G2.5b change (volcanic banding and frozen
 *   lava flows, y-banded rock, ocean-floor and lakeshore materials, real forest
 *   density, per-tree variety, undergrowth) lives downstream of the heightfield,
 *   so the hashes below are deliberately **unchanged**: the field engine is the
 *   contract, and G2.5b did not touch it. Compiled worlds from before G2.5b do
 *   not reproduce block-for-block; their terrain shape does.
 * - **G2.5c (snow climate gating + open-basin water)** — authorized reroll of
 *   the *compiled world* only; both hashes below are again deliberately
 *   **unchanged**. Snow now needs an altitude-corrected climate temperature as
 *   well as the relief snow line, but the gate is opt-in at the `classify`
 *   seam (`MarkerOptions.temperature`) and this request passes no climate
 *   field, so classification here is bit-identical. Open-rimmed `water: true`
 *   basins now settle at the highest fluid-stable level instead of compiling
 *   dry, which moves water blocks, never terrain — the request above has no
 *   basin at all. Compiled worlds from before G2.5c do not reproduce
 *   block-for-block; their terrain shape does.
 * - **G4.5a (composition)** — authorized reroll of the *classification* only.
 *   The **field hash below is deliberately unchanged**, and that is the hard
 *   check: every G4.5a change is downstream of the heightfield. What did move
 *   is hydrology. A `river` with `flooded: "auto"` that reaches no ocean is now
 *   demoted to a chain of ponds instead of compiling as a bone-dry trench, and
 *   this request's `riv` is exactly such a river — its region never dips to
 *   sea level, so the flood fill had nothing to propagate from. The ponds are
 *   recorded as basins, the lake mask picks them up, and the columns under them
 *   reclassify from soil to lake and lakeshore. `field.values` is never
 *   touched by the demotion, which is why only the second hash below moved.
 *   The other three defects G4.5a fixed (settlement clearing, canopy clipping
 *   against buildings, plaza paving) live in the compiler and cannot reach this
 *   file at all. Compiled worlds from before G4.5a do not reproduce
 *   block-for-block; their terrain shape does.
 * - **G5 (roads, treelines, long rivers)** — authorized reroll of the
 *   *compiled world* only. **Both hashes below are deliberately unchanged**,
 *   and that is again the hard check. Six changes landed and each was designed
 *   to stay out of this fixture:
 *     * corridor verbs gained a second, much longer meander octave whose
 *       amplitude is a share of *course length*. It ramps in from 120 blocks
 *       of course and every corridor in the request below is shorter than
 *       that, so `longRamp` is exactly 0 and `makeCorridorShape` is
 *       bit-identical to G2.5a's here;
 *     * roads gained a bridge (priced water crossings, plank decks), a
 *       wall-hug routing penalty, a perpendicular door approach, a cut bias
 *       (`ROAD_FILL_BAND` 2 → 1) and graded shoulders;
 *     * the settlement clearing's distance threshold and a forest node's own
 *       area boundary are both wobbled by low-frequency noise;
 *     * the in-wall accent-log share halved, 0.07 → 0.035.
 *   All six live in `@terrainist/compiler` or in the building grammar, both of
 *   which are downstream of the heightfield and neither of which this file
 *   imports. Compiled worlds from before G5 do not reproduce block-for-block;
 *   their terrain shape does.
 * - **G4.5c micro-fixes** — authorized reroll of the *compiled world* only.
 *   **Both hashes below are deliberately unchanged.** Three render-review
 *   defects were fixed, all of them in `@terrainist/compiler`:
 *     * fallen-log decor now keeps a four-block apron off every footprint,
 *       road corridor and the plaza, so no deadwood lies against a wall;
 *     * a forest node's `area` boundary — not just its density taper — carries
 *       the low-frequency edge wobble, so a `zone` patch stops on a bent line
 *       rather than on the nine-grid's rectangle. This moves trees, which is
 *       the reroll;
 *     * a building underpins every apron block at or below its floor plane
 *       down to solid ground, so a doorstep on a slope cannot float.
 *   None of the three imports this file's field engine. Compiled worlds from
 *   before G4.5c do not reproduce block-for-block; their terrain shape does.
 * - **G4.7 (second walkthrough: stairs, chimneys, granaries, lamp posts)** —
 *   authorized reroll of the *compiled world* only. **Both hashes below are
 *   deliberately unchanged**, and once again that is the check that matters:
 *   every change is downstream of the heightfield. Four defects a human found
 *   walking the village, and two of them proved the physics lint had blind
 *   spots:
 *     * an interior stair flight now stands one cell off the wall it climbs,
 *       with the cell at its foot left as an open approach and the stairwell
 *       cut over the approach as well as the run. A flight with its front face
 *       buried in the wall is mountable only from the side, and the half-block
 *       gap left there is narrower than a player;
 *     * the chimney moved out of the room and into the wall: the flue occupies
 *       wall cells flush with the face, the hearth is an opening in that face,
 *       and the head's corbel is clipped to the footprint. It used to stand on
 *       an interior column and run floor-to-ceiling through the middle of a
 *       smithy;
 *     * a granary's hay is stacked one to three high against the walls, on at
 *       most a quarter of the floor, instead of checkerboarding the whole of
 *       it — a pattern whose free cells only touched at their corners;
 *     * road lamp posts are planted after the shoulder blend rather than
 *       before it, so they stand on the ground the emitter will actually lay
 *       rather than on a height a later pass moved;
 *     * the smithy's forge moved to the east wall, because on the west it
 *       sealed the stair approach off from the shop floor.
 *   All of it lives in the building grammar and in `@terrainist/compiler`;
 *   neither imports this file's field engine. Compiled worlds from before G4.7
 *   do not reproduce block-for-block; their terrain shape does.
 * - **G5/G6-pre integration (rounds A–E)** — authorized reroll of the
 *   *compiled world* only. **Both hashes below are deliberately unchanged**,
 *   and the reason is the same one it has been every time: nothing in the
 *   round is upstream of the heightfield. What moved, and why each is a
 *   reroll rather than a regression:
 *     * the building grammar resolves `roof`, `windowShape` and
 *       `windowRhythm` from the **archetype** when the params do not name
 *       them, so a church gets tall lights and a warehouse gets almost none
 *       without an author saying so. Explicit params still win, so any node
 *       that named one is byte-identical;
 *     * `wing` is wired end to end — a Loam document can now ask for an L or
 *       a T — and the fit-out reasons about `meta.floorCells` rather than the
 *       main rect's interior, so a wing gets furniture, its upper storey gets
 *       a fit-out, and the walkability guard spans both rects;
 *     * the cellar decoration goes through the same walkability guard as
 *       everything else. Two crates drawn independently used to be able to box
 *       a corner in, which the physics lint duly reported;
 *     * `prop.place@0` is wired into the structure pass, so a document's piers,
 *       boats, carts, rails and fountains are built. They are placed against
 *       the *finished* ground, after the roads;
 *     * a building underpins its apron a second time, after the roads have
 *       cut, because a lane arriving at a door can drop the column a porch
 *       lamp stands in. The fill stops at a tunnel roof rather than punching
 *       through it;
 *     * `examples/hillside-village.loam.json` gained a chapel (an L, tunnelled
 *       to the great hall), a market stall, a pier and a rowboat, which moves
 *       every seeded draw downstream of them in that document.
 *   All of it lives in `@terrainist/stdlib`'s structures or in
 *   `@terrainist/compiler`; neither imports this file's field engine.
 *   Compiled worlds from before this round do not reproduce block-for-block;
 *   their terrain shape does.
 * - **Overnight-program final fix round (2026-07-29)** — authorized reroll of
 *   the *compiled world* only, and only of worlds that carry a tunnel or a
 *   large ground prop. **Both hashes below are deliberately unchanged**: the
 *   round touches the structure pass and the prop placer, neither of which is
 *   upstream of the heightfield. What moved:
 *     * the tunnel router now tests its roof margin over the **whole bore
 *       swath** rather than over the centre line alone. The centre-line test
 *       was strictly weaker than the one `checkTunnelIntegrity` applies, which
 *       is how a GLM-authored delta port produced `LOAM-W408` from a route the
 *       router had certified. Every gallery on rolling ground therefore takes
 *       a slightly different — and legal — line; the deltaport's own route
 *       went from 475 cells to 477;
 *     * a support frame is no longer built at the foot of a rise. Its lantern
 *       hangs in exactly the block a walking agent needs clear to climb the
 *       step, so a gallery could be walked down and not back up. Latent since
 *       the frames were added and unmasked by the reroute above, which is a
 *       reminder that the traversal lint is load-bearing;
 *     * a land prop's relief tolerance scales with its footprint, and a prop
 *       on a site rougher than one block levels a pad under itself. Small
 *       props are on the old rule and emit no pad, so nothing that fitted
 *       before has moved — only props that could not be placed at all.
 *   Compiled worlds from before this round reproduce block-for-block unless
 *   they contain a tunnel; their terrain shape is unchanged either way.
 */

const hex = (b: Uint8Array): string => Buffer.from(b).toString("hex");

function hashField(values: Float64Array): string {
  return hex(blake3(new Uint8Array(values.buffer, values.byteOffset, values.byteLength)));
}

const REQUEST: TerrainFieldRequest = {
  region: centeredRegion(64, 64),
  worldSeed: 813205,
  nodePath: "world.terrain",
  params: {
    ridged: true,
    amplitude: 72,
    erosionPasses: 2,
    warp: { amount: 20, frequency: 0.01 },
    continentalness: { frequency: 0.0009, seaFraction: 0.45 },
    curve: [
      [0, 0],
      [0.5, 0.35],
      [1, 1],
    ],
  },
  edits: [
    {
      id: "the_divide",
      verb: "ridge",
      course: [
        [0.15, 0.5],
        [0.5, 0.42],
        [0.85, 0.55],
      ],
      width: 48,
      height: 60,
      profile: "sharp",
    },
    { id: "v", verb: "volcano", zone: "northeast" },
    {
      id: "riv",
      verb: "river",
      course: [
        [0.1, 0.1],
        [0.9, 0.9],
      ],
    },
  ],
};

describe("golden field", () => {
  it("matches the pinned heightfield hash", () => {
    const r = buildTerrainField(REQUEST);
    expect(hashField(r.field.values)).toBe(
      "7da8baeaa1db075ead0ac54eb3643a6c44c5a6ea8f9d1e786291ee105aa6faf9",
    );
  });

  it("matches the pinned classification hash", () => {
    const r = buildTerrainField(REQUEST);
    expect(hex(blake3(r.classification.classes))).toBe(
      "41841b2db16f77391cad154f2f650de469c859080f44764e84c547bce663bfb8",
    );
  });

  it("is byte-identical when built twice", () => {
    const a = buildTerrainField(REQUEST);
    const b = buildTerrainField(REQUEST);
    expect(hashField(a.field.values)).toBe(hashField(b.field.values));
    expect(hex(blake3(a.classification.classes))).toBe(hex(blake3(b.classification.classes)));
    expect(a.classification.markers).toEqual(b.classification.markers);
    expect(a.edits.markers).toEqual(b.edits.markers);
    expect(a.edits.order).toEqual(b.edits.order);
    expect(a.worldSeed).toBe(b.worldSeed);
  });

  it("rerolls on seedSalt and only on seedSalt", () => {
    const base = buildTerrainField(REQUEST);
    const salted = buildTerrainField({ ...REQUEST, seedSalt: "a" });
    expect(hashField(salted.field.values)).not.toBe(hashField(base.field.values));
    // the same salt reproduces
    expect(hashField(buildTerrainField({ ...REQUEST, seedSalt: "a" }).field.values)).toBe(
      hashField(salted.field.values),
    );
  });

  it("rerolls on worldSeed and on nodePath", () => {
    const base = hashField(buildTerrainField(REQUEST).field.values);
    expect(hashField(buildTerrainField({ ...REQUEST, worldSeed: 813206 }).field.values)).not.toBe(
      base,
    );
    expect(
      hashField(buildTerrainField({ ...REQUEST, nodePath: "world.other" }).field.values),
    ).not.toBe(base);
  });

  it("accepts every §6.1 world-seed spelling with the same result", () => {
    const a = buildTerrainField({ ...REQUEST, worldSeed: 813205 });
    const b = buildTerrainField({ ...REQUEST, worldSeed: "813205" });
    const c = buildTerrainField({ ...REQUEST, worldSeed: 813205n });
    expect(hashField(b.field.values)).toBe(hashField(a.field.values));
    expect(hashField(c.field.values)).toBe(hashField(a.field.values));
  });

  it("reports the resolved world seed for level.dat", () => {
    expect(buildTerrainField({ ...REQUEST, worldSeed: "misty fjords" }).worldSeed).toBe(
      10552861534622507875n,
    );
  });
});
