import { blake3 } from "@noble/hashes/blake3.js";
import { describe, expect, it } from "vitest";

import { centeredRegion } from "../src/field/index.js";
import { buildTerrainField, type TerrainFieldRequest } from "../src/index.js";

/**
 * The determinism contract, made testable: same spec + same seed → byte-identical
 * field. These hashes are **pinned**. If one of them changes, the change rerolls
 * every world ever generated by this toolchain — so it must be a deliberate,
 * versioned decision, never an accidental consequence of a refactor.
 */

const hex = (b: Uint8Array): string => Buffer.from(b).toString("hex");

function hashField(values: Float64Array): string {
  return hex(blake3(new Uint8Array(values.buffer, values.byteOffset, values.byteLength)));
}

const REQUEST: TerrainFieldRequest = {
  region: centeredRegion(64, 64),
  worldSeed: 813205,
  nodePath: "world.terrain",
  params: {
    ridged: true,
    amplitude: 72,
    erosionPasses: 2,
    warp: { amount: 20, frequency: 0.01 },
    continentalness: { frequency: 0.0009, seaFraction: 0.45 },
    curve: [
      [0, 0],
      [0.5, 0.35],
      [1, 1],
    ],
  },
  edits: [
    {
      id: "the_divide",
      verb: "ridge",
      course: [
        [0.15, 0.5],
        [0.5, 0.42],
        [0.85, 0.55],
      ],
      width: 48,
      height: 60,
      profile: "sharp",
    },
    { id: "v", verb: "volcano", zone: "northeast" },
    {
      id: "riv",
      verb: "river",
      course: [
        [0.1, 0.1],
        [0.9, 0.9],
      ],
    },
  ],
};

describe("golden field", () => {
  it("matches the pinned heightfield hash", () => {
    const r = buildTerrainField(REQUEST);
    expect(hashField(r.field.values)).toBe(
      "63b635fb77c5b10aaf69ae8c8e52acaba09c019d06f4d0199e46a97fb3553b68",
    );
  });

  it("matches the pinned classification hash", () => {
    const r = buildTerrainField(REQUEST);
    expect(hex(blake3(r.classification.classes))).toBe(
      "79d5740c52c3eedabb52f95da3ff3a310dd0dcf3cca8a8e6b495599169283b46",
    );
  });

  it("is byte-identical when built twice", () => {
    const a = buildTerrainField(REQUEST);
    const b = buildTerrainField(REQUEST);
    expect(hashField(a.field.values)).toBe(hashField(b.field.values));
    expect(hex(blake3(a.classification.classes))).toBe(hex(blake3(b.classification.classes)));
    expect(a.classification.markers).toEqual(b.classification.markers);
    expect(a.edits.markers).toEqual(b.edits.markers);
    expect(a.edits.order).toEqual(b.edits.order);
    expect(a.worldSeed).toBe(b.worldSeed);
  });

  it("rerolls on seedSalt and only on seedSalt", () => {
    const base = buildTerrainField(REQUEST);
    const salted = buildTerrainField({ ...REQUEST, seedSalt: "a" });
    expect(hashField(salted.field.values)).not.toBe(hashField(base.field.values));
    // the same salt reproduces
    expect(hashField(buildTerrainField({ ...REQUEST, seedSalt: "a" }).field.values)).toBe(
      hashField(salted.field.values),
    );
  });

  it("rerolls on worldSeed and on nodePath", () => {
    const base = hashField(buildTerrainField(REQUEST).field.values);
    expect(hashField(buildTerrainField({ ...REQUEST, worldSeed: 813206 }).field.values)).not.toBe(
      base,
    );
    expect(
      hashField(buildTerrainField({ ...REQUEST, nodePath: "world.other" }).field.values),
    ).not.toBe(base);
  });

  it("accepts every §6.1 world-seed spelling with the same result", () => {
    const a = buildTerrainField({ ...REQUEST, worldSeed: 813205 });
    const b = buildTerrainField({ ...REQUEST, worldSeed: "813205" });
    const c = buildTerrainField({ ...REQUEST, worldSeed: 813205n });
    expect(hashField(b.field.values)).toBe(hashField(a.field.values));
    expect(hashField(c.field.values)).toBe(hashField(a.field.values));
  });

  it("reports the resolved world seed for level.dat", () => {
    expect(buildTerrainField({ ...REQUEST, worldSeed: "misty fjords" }).worldSeed).toBe(
      10552861534622507875n,
    );
  });
});
